2025-06-27 11:33:03.398 | INFO     | __main__:main:155 - Args: Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_rank=0, num_machines=1, machine_rank=0, exp_file='exps/example/mot/yolox_x_mix_det.py', fp16=True, fuse=True, trt=False, test=False, speed=False, opts=[], ckpt='pretrained/bytetrack_x_mot17.pth.tar', conf=0.01, nms=0.7, tsize=None, seed=None, track_thresh=0.6, track_buffer=30, match_thresh=0.9, min_box_area=100, mot20=False)
2025-06-27 11:33:03.796 | INFO     | __main__:main:165 - Model Summary: Params: 99.00M, Gflops: 793.21
2025-06-27 11:33:03.796 | INFO     | yolox.data.datasets.mot:__init__:39 - loading annotations into memory...
2025-06-27 11:33:03.796 | ERROR    | yolox.core.launch:launch:90 - An error has been caught in function 'launch', process 'MainProcess' (10737), thread 'MainThread' (140651378561152):
Traceback (most recent call last):

  File "/home/stas/ID-REID/ByteTrack/tools/track.py", line 287, in <module>
    launch(
    └ <function launch at 0x7feb36f2d160>

> File "/home/stas/ID-REID/ByteTrack/yolox/core/launch.py", line 90, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x7feae4b795e0>

  File "/home/stas/ID-REID/ByteTrack/tools/track.py", line 168, in main
    val_loader = exp.get_eval_loader(args.batch_size, is_distributed, args.test)
                 │   │               │    │           │               │    └ False
                 │   │               │    │           │               └ Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_ra...
                 │   │               │    │           └ False
                 │   │               │    └ 1
                 │   │               └ Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_ra...
                 │   └ <function Exp.get_eval_loader at 0x7feae4b79ee0>
                 └ ╒══════════════════╤═════════════════════════════════════════════════════════════════════════════════════════════════════════...

  File "/home/stas/ID-REID/ByteTrack/exps/example/mot/yolox_x_mix_det.py", line 97, in get_eval_loader
    valdataset = MOTDataset(
                 └ <class 'yolox.data.datasets.mot.MOTDataset'>

  File "/home/stas/ID-REID/ByteTrack/yolox/data/datasets/mot.py", line 39, in __init__
    self.coco = COCO(os.path.join(self.data_dir, "annotations", self.json_file))
    │           │    │  │    │    │    │                        │    └ 'test.json'
    │           │    │  │    │    │    │                        └ <yolox.data.datasets.mot.MOTDataset object at 0x7feb697643a0>
    │           │    │  │    │    │    └ '/home/stas/ID-REID/ByteTrack/datasets/sequences'
    │           │    │  │    │    └ <yolox.data.datasets.mot.MOTDataset object at 0x7feb697643a0>
    │           │    │  │    └ <function join at 0x7febf35a9940>
    │           │    │  └ <module 'posixpath' from '/usr/local/lib/python3.9/posixpath.py'>
    │           │    └ <module 'os' from '/usr/local/lib/python3.9/os.py'>
    │           └ <class 'pycocotools.coco.COCO'>
    └ <yolox.data.datasets.mot.MOTDataset object at 0x7feb697643a0>

  File "/home/stas/ID-REID/ByteTrack/.venv/lib/python3.9/site-packages/pycocotools/coco.py", line 84, in __init__
    dataset = json.load(open(annotation_file, 'r'))
              │    │         └ '/home/stas/ID-REID/ByteTrack/datasets/sequences/annotations/test.json'
              │    └ <function load at 0x7febeeda4310>
              └ <module 'json' from '/usr/local/lib/python3.9/json/__init__.py'>

FileNotFoundError: [Errno 2] No such file or directory: '/home/stas/ID-REID/ByteTrack/datasets/sequences/annotations/test.json'
2025-06-27 11:33:40.064 | INFO     | __main__:main:155 - Args: Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_rank=0, num_machines=1, machine_rank=0, exp_file='exps/example/mot/yolox_x_mix_det.py', fp16=True, fuse=True, trt=False, test=False, speed=False, opts=[], ckpt='pretrained/bytetrack_x_mot17.pth.tar', conf=0.01, nms=0.7, tsize=None, seed=None, track_thresh=0.6, track_buffer=30, match_thresh=0.9, min_box_area=100, mot20=False)
2025-06-27 11:33:40.465 | INFO     | __main__:main:165 - Model Summary: Params: 99.00M, Gflops: 793.21
2025-06-27 11:33:40.466 | INFO     | yolox.data.datasets.mot:__init__:39 - loading annotations into memory...
2025-06-27 11:33:40.541 | INFO     | yolox.data.datasets.mot:__init__:39 - Done (t=0.08s)
2025-06-27 11:33:40.542 | INFO     | pycocotools.coco:__init__:88 - creating index...
2025-06-27 11:33:40.545 | INFO     | pycocotools.coco:__init__:88 - index created!
2025-06-27 11:33:40.563 | ERROR    | yolox.core.launch:launch:90 - An error has been caught in function 'launch', process 'MainProcess' (11170), thread 'MainThread' (139874968838272):
Traceback (most recent call last):

  File "/home/stas/ID-REID/ByteTrack/tools/track.py", line 287, in <module>
    launch(
    └ <function launch at 0x7f367152b160>

> File "/home/stas/ID-REID/ByteTrack/yolox/core/launch.py", line 90, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x7f361f1765e0>

  File "/home/stas/ID-REID/ByteTrack/tools/track.py", line 168, in main
    val_loader = exp.get_eval_loader(args.batch_size, is_distributed, args.test)
                 │   │               │    │           │               │    └ False
                 │   │               │    │           │               └ Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_ra...
                 │   │               │    │           └ False
                 │   │               │    └ 1
                 │   │               └ Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_ra...
                 │   └ <function Exp.get_eval_loader at 0x7f361f176ee0>
                 └ ╒══════════════════╤═════════════════════════════════════════════════════════════════════════════════════════════════════════...

  File "/home/stas/ID-REID/ByteTrack/exps/example/mot/yolox_x_mix_det.py", line 97, in get_eval_loader
    valdataset = MOTDataset(
                 └ <class 'yolox.data.datasets.mot.MOTDataset'>

  File "/home/stas/ID-REID/ByteTrack/yolox/data/datasets/mot.py", line 44, in __init__
    self.annotations = self._load_coco_annotations()
    │                  │    └ <function MOTDataset._load_coco_annotations at 0x7f3660b1e9d0>
    │                  └ <yolox.data.datasets.mot.MOTDataset object at 0x7f361f181520>
    └ <yolox.data.datasets.mot.MOTDataset object at 0x7f361f181520>

  File "/home/stas/ID-REID/ByteTrack/yolox/data/datasets/mot.py", line 53, in _load_coco_annotations
    return [self.load_anno_from_ids(_ids) for _ids in self.ids]
            │    │                                    │    └ [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 3...
            │    │                                    └ <yolox.data.datasets.mot.MOTDataset object at 0x7f361f181520>
            │    └ <function MOTDataset.load_anno_from_ids at 0x7f3660b1ea60>
            └ <yolox.data.datasets.mot.MOTDataset object at 0x7f361f181520>

  File "/home/stas/ID-REID/ByteTrack/yolox/data/datasets/mot.py", line 53, in <listcomp>
    return [self.load_anno_from_ids(_ids) for _ids in self.ids]
            │    │                  │         │       │    └ [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 3...
            │    │                  │         │       └ <yolox.data.datasets.mot.MOTDataset object at 0x7f361f181520>
            │    │                  │         └ 1701
            │    │                  └ 1701
            │    └ <function MOTDataset.load_anno_from_ids at 0x7f3660b1ea60>
            └ <yolox.data.datasets.mot.MOTDataset object at 0x7f361f181520>

  File "/home/stas/ID-REID/ByteTrack/yolox/data/datasets/mot.py", line 78, in load_anno_from_ids
    cls = self.class_ids.index(obj["category_id"])
          │    │         │     └ {'id': 20410, 'category_id': -1, 'image_id': 1701, 'track_id': 1498, 'bbox': [683.0, 121.0, 22.64900016784668, 68.15200042724...
          │    │         └ <method 'index' of 'list' objects>
          │    └ [1]
          └ <yolox.data.datasets.mot.MOTDataset object at 0x7f361f181520>

ValueError: -1 is not in list
2025-06-27 11:35:58.898 | INFO     | __main__:main:155 - Args: Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_rank=0, num_machines=1, machine_rank=0, exp_file='exps/example/mot/yolox_x_mix_det.py', fp16=True, fuse=True, trt=False, test=False, speed=False, opts=[], ckpt='pretrained/bytetrack_x_mot17.pth.tar', conf=0.01, nms=0.7, tsize=None, seed=None, track_thresh=0.6, track_buffer=30, match_thresh=0.9, min_box_area=100, mot20=False)
2025-06-27 11:35:59.298 | INFO     | __main__:main:165 - Model Summary: Params: 99.00M, Gflops: 793.21
2025-06-27 11:35:59.299 | INFO     | yolox.data.datasets.mot:__init__:39 - loading annotations into memory...
2025-06-27 11:35:59.373 | INFO     | yolox.data.datasets.mot:__init__:39 - Done (t=0.07s)
2025-06-27 11:35:59.373 | INFO     | pycocotools.coco:__init__:88 - creating index...
2025-06-27 11:35:59.377 | INFO     | pycocotools.coco:__init__:88 - index created!
2025-06-27 11:35:59.394 | ERROR    | yolox.core.launch:launch:90 - An error has been caught in function 'launch', process 'MainProcess' (12468), thread 'MainThread' (140592883372160):
Traceback (most recent call last):

  File "/home/stas/ID-REID/ByteTrack/tools/track.py", line 287, in <module>
    launch(
    └ <function launch at 0x7fdd985d1160>

> File "/home/stas/ID-REID/ByteTrack/yolox/core/launch.py", line 90, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x7fdd4621d5e0>

  File "/home/stas/ID-REID/ByteTrack/tools/track.py", line 168, in main
    val_loader = exp.get_eval_loader(args.batch_size, is_distributed, args.test)
                 │   │               │    │           │               │    └ False
                 │   │               │    │           │               └ Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_ra...
                 │   │               │    │           └ False
                 │   │               │    └ 1
                 │   │               └ Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_ra...
                 │   └ <function Exp.get_eval_loader at 0x7fdd4621dee0>
                 └ ╒══════════════════╤═════════════════════════════════════════════════════════════════════════════════════════════════════════...

  File "/home/stas/ID-REID/ByteTrack/exps/example/mot/yolox_x_mix_det.py", line 97, in get_eval_loader
    valdataset = MOTDataset(
                 └ <class 'yolox.data.datasets.mot.MOTDataset'>

  File "/home/stas/ID-REID/ByteTrack/yolox/data/datasets/mot.py", line 44, in __init__
    self.annotations = self._load_coco_annotations()
    │                  │    └ <function MOTDataset._load_coco_annotations at 0x7fdd87bc59d0>
    │                  └ <yolox.data.datasets.mot.MOTDataset object at 0x7fdd46228cd0>
    └ <yolox.data.datasets.mot.MOTDataset object at 0x7fdd46228cd0>

  File "/home/stas/ID-REID/ByteTrack/yolox/data/datasets/mot.py", line 53, in _load_coco_annotations
    return [self.load_anno_from_ids(_ids) for _ids in self.ids]
            │    │                                    │    └ [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 3...
            │    │                                    └ <yolox.data.datasets.mot.MOTDataset object at 0x7fdd46228cd0>
            │    └ <function MOTDataset.load_anno_from_ids at 0x7fdd87bc5a60>
            └ <yolox.data.datasets.mot.MOTDataset object at 0x7fdd46228cd0>

  File "/home/stas/ID-REID/ByteTrack/yolox/data/datasets/mot.py", line 53, in <listcomp>
    return [self.load_anno_from_ids(_ids) for _ids in self.ids]
            │    │                  │         │       │    └ [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 3...
            │    │                  │         │       └ <yolox.data.datasets.mot.MOTDataset object at 0x7fdd46228cd0>
            │    │                  │         └ 1701
            │    │                  └ 1701
            │    └ <function MOTDataset.load_anno_from_ids at 0x7fdd87bc5a60>
            └ <yolox.data.datasets.mot.MOTDataset object at 0x7fdd46228cd0>

  File "/home/stas/ID-REID/ByteTrack/yolox/data/datasets/mot.py", line 78, in load_anno_from_ids
    cls = self.class_ids.index(obj["category_id"])
          │    │         │     └ {'id': 20410, 'category_id': -1, 'image_id': 1701, 'track_id': 1498, 'bbox': [683.0, 121.0, 22.64900016784668, 68.15200042724...
          │    │         └ <method 'index' of 'list' objects>
          │    └ [1]
          └ <yolox.data.datasets.mot.MOTDataset object at 0x7fdd46228cd0>

ValueError: -1 is not in list
2025-06-27 11:36:44.086 | INFO     | __main__:main:155 - Args: Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_rank=0, num_machines=1, machine_rank=0, exp_file='exps/example/mot/yolox_x_mix_det.py', fp16=True, fuse=True, trt=False, test=False, speed=False, opts=[], ckpt='pretrained/bytetrack_x_mot17.pth.tar', conf=0.01, nms=0.7, tsize=None, seed=None, track_thresh=0.6, track_buffer=30, match_thresh=0.9, min_box_area=100, mot20=False)
2025-06-27 11:36:44.486 | INFO     | __main__:main:165 - Model Summary: Params: 99.00M, Gflops: 793.21
2025-06-27 11:36:44.486 | INFO     | yolox.data.datasets.mot:__init__:39 - loading annotations into memory...
2025-06-27 11:36:44.561 | INFO     | yolox.data.datasets.mot:__init__:39 - Done (t=0.07s)
2025-06-27 11:36:44.561 | INFO     | pycocotools.coco:__init__:88 - creating index...
2025-06-27 11:36:44.564 | INFO     | pycocotools.coco:__init__:88 - index created!
2025-06-27 11:36:44.582 | ERROR    | yolox.core.launch:launch:90 - An error has been caught in function 'launch', process 'MainProcess' (12974), thread 'MainThread' (139864964817024):
Traceback (most recent call last):

  File "/home/stas/ID-REID/ByteTrack/tools/track.py", line 287, in <module>
    launch(
    └ <function launch at 0x7f341d096160>

> File "/home/stas/ID-REID/ByteTrack/yolox/core/launch.py", line 90, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x7f33cace25e0>

  File "/home/stas/ID-REID/ByteTrack/tools/track.py", line 168, in main
    val_loader = exp.get_eval_loader(args.batch_size, is_distributed, args.test)
                 │   │               │    │           │               │    └ False
                 │   │               │    │           │               └ Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_ra...
                 │   │               │    │           └ False
                 │   │               │    └ 1
                 │   │               └ Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_ra...
                 │   └ <function Exp.get_eval_loader at 0x7f33cace2dc0>
                 └ ╒══════════════════╤═════════════════════════════════════════════════════════════════════════════════════════════════════════...

  File "/home/stas/ID-REID/ByteTrack/exps/example/mot/yolox_x_mix_det.py", line 97, in get_eval_loader
    valdataset = MOTDataset(
                 └ <class 'yolox.data.datasets.mot.MOTDataset'>

  File "/home/stas/ID-REID/ByteTrack/yolox/data/datasets/mot.py", line 44, in __init__
    self.annotations = self._load_coco_annotations()
    │                  │    └ <function MOTDataset._load_coco_annotations at 0x7f340c68a9d0>
    │                  └ <yolox.data.datasets.mot.MOTDataset object at 0x7f34519053a0>
    └ <yolox.data.datasets.mot.MOTDataset object at 0x7f34519053a0>

  File "/home/stas/ID-REID/ByteTrack/yolox/data/datasets/mot.py", line 53, in _load_coco_annotations
    return [self.load_anno_from_ids(_ids) for _ids in self.ids]
            │    │                                    │    └ [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 3...
            │    │                                    └ <yolox.data.datasets.mot.MOTDataset object at 0x7f34519053a0>
            │    └ <function MOTDataset.load_anno_from_ids at 0x7f340c68aa60>
            └ <yolox.data.datasets.mot.MOTDataset object at 0x7f34519053a0>

  File "/home/stas/ID-REID/ByteTrack/yolox/data/datasets/mot.py", line 53, in <listcomp>
    return [self.load_anno_from_ids(_ids) for _ids in self.ids]
            │    │                  │         │       │    └ [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 3...
            │    │                  │         │       └ <yolox.data.datasets.mot.MOTDataset object at 0x7f34519053a0>
            │    │                  │         └ 1701
            │    │                  └ 1701
            │    └ <function MOTDataset.load_anno_from_ids at 0x7f340c68aa60>
            └ <yolox.data.datasets.mot.MOTDataset object at 0x7f34519053a0>

  File "/home/stas/ID-REID/ByteTrack/yolox/data/datasets/mot.py", line 78, in load_anno_from_ids
    cls = self.class_ids.index(obj["category_id"])
          │    │         │     └ {'id': 20410, 'category_id': -1, 'image_id': 1701, 'track_id': 1498, 'bbox': [683.0, 121.0, 22.64900016784668, 68.15200042724...
          │    │         └ <method 'index' of 'list' objects>
          │    └ [1]
          └ <yolox.data.datasets.mot.MOTDataset object at 0x7f34519053a0>

ValueError: -1 is not in list
2025-06-27 11:43:00.536 | INFO     | __main__:main:155 - Args: Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_rank=0, num_machines=1, machine_rank=0, exp_file='exps/example/mot/yolox_x_mix_det.py', fp16=True, fuse=True, trt=False, test=False, speed=False, opts=[], ckpt='pretrained/bytetrack_x_mot17.pth.tar', conf=0.01, nms=0.7, tsize=None, seed=None, track_thresh=0.6, track_buffer=30, match_thresh=0.9, min_box_area=100, mot20=False)
2025-06-27 11:43:00.932 | INFO     | __main__:main:165 - Model Summary: Params: 99.00M, Gflops: 793.21
2025-06-27 11:43:00.932 | INFO     | yolox.data.datasets.mot:__init__:39 - loading annotations into memory...
2025-06-27 11:43:01.008 | INFO     | yolox.data.datasets.mot:__init__:39 - Done (t=0.08s)
2025-06-27 11:43:01.008 | INFO     | pycocotools.coco:__init__:88 - creating index...
2025-06-27 11:43:01.011 | INFO     | pycocotools.coco:__init__:88 - index created!
2025-06-27 11:43:01.029 | ERROR    | yolox.core.launch:launch:90 - An error has been caught in function 'launch', process 'MainProcess' (16047), thread 'MainThread' (140696026267776):
Traceback (most recent call last):

  File "/home/stas/ID-REID/ByteTrack/tools/track.py", line 287, in <module>
    launch(
    └ <function launch at 0x7ff59c28c160>

> File "/home/stas/ID-REID/ByteTrack/yolox/core/launch.py", line 90, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x7ff549ed85e0>

  File "/home/stas/ID-REID/ByteTrack/tools/track.py", line 168, in main
    val_loader = exp.get_eval_loader(args.batch_size, is_distributed, args.test)
                 │   │               │    │           │               │    └ False
                 │   │               │    │           │               └ Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_ra...
                 │   │               │    │           └ False
                 │   │               │    └ 1
                 │   │               └ Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_ra...
                 │   └ <function Exp.get_eval_loader at 0x7ff549ed8dc0>
                 └ ╒══════════════════╤═════════════════════════════════════════════════════════════════════════════════════════════════════════...

  File "/home/stas/ID-REID/ByteTrack/exps/example/mot/yolox_x_mix_det.py", line 97, in get_eval_loader
    valdataset = MOTDataset(
                 └ <class 'yolox.data.datasets.mot.MOTDataset'>

  File "/home/stas/ID-REID/ByteTrack/yolox/data/datasets/mot.py", line 44, in __init__
    self.annotations = self._load_coco_annotations()
    │                  │    └ <function MOTDataset._load_coco_annotations at 0x7ff58b8809d0>
    │                  └ <yolox.data.datasets.mot.MOTDataset object at 0x7ff5c0bc53a0>
    └ <yolox.data.datasets.mot.MOTDataset object at 0x7ff5c0bc53a0>

  File "/home/stas/ID-REID/ByteTrack/yolox/data/datasets/mot.py", line 53, in _load_coco_annotations
    return [self.load_anno_from_ids(_ids) for _ids in self.ids]
            │    │                                    │    └ [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 3...
            │    │                                    └ <yolox.data.datasets.mot.MOTDataset object at 0x7ff5c0bc53a0>
            │    └ <function MOTDataset.load_anno_from_ids at 0x7ff58b880a60>
            └ <yolox.data.datasets.mot.MOTDataset object at 0x7ff5c0bc53a0>

  File "/home/stas/ID-REID/ByteTrack/yolox/data/datasets/mot.py", line 53, in <listcomp>
    return [self.load_anno_from_ids(_ids) for _ids in self.ids]
            │    │                  │         │       │    └ [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 3...
            │    │                  │         │       └ <yolox.data.datasets.mot.MOTDataset object at 0x7ff5c0bc53a0>
            │    │                  │         └ 1701
            │    │                  └ 1701
            │    └ <function MOTDataset.load_anno_from_ids at 0x7ff58b880a60>
            └ <yolox.data.datasets.mot.MOTDataset object at 0x7ff5c0bc53a0>

  File "/home/stas/ID-REID/ByteTrack/yolox/data/datasets/mot.py", line 78, in load_anno_from_ids
    cls = self.class_ids.index(obj["category_id"])
          │    │         │     └ {'id': 20410, 'category_id': -1, 'image_id': 1701, 'track_id': 1498, 'bbox': [683.0, 121.0, 22.64900016784668, 68.15200042724...
          │    │         └ <method 'index' of 'list' objects>
          │    └ [1]
          └ <yolox.data.datasets.mot.MOTDataset object at 0x7ff5c0bc53a0>

ValueError: -1 is not in list
2025-06-27 11:44:13.303 | INFO     | __main__:main:155 - Args: Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_rank=0, num_machines=1, machine_rank=0, exp_file='exps/example/mot/yolox_x_mix_det.py', fp16=True, fuse=True, trt=False, test=False, speed=False, opts=[], ckpt='pretrained/bytetrack_x_mot17.pth.tar', conf=0.01, nms=0.7, tsize=None, seed=None, track_thresh=0.6, track_buffer=30, match_thresh=0.9, min_box_area=100, mot20=False)
2025-06-27 11:44:13.694 | INFO     | __main__:main:165 - Model Summary: Params: 99.00M, Gflops: 793.21
2025-06-27 11:44:13.695 | INFO     | yolox.data.datasets.mot:__init__:39 - loading annotations into memory...
2025-06-27 11:44:13.971 | INFO     | yolox.data.datasets.mot:__init__:39 - Done (t=0.28s)
2025-06-27 11:44:13.971 | INFO     | pycocotools.coco:__init__:88 - creating index...
2025-06-27 11:44:13.989 | INFO     | pycocotools.coco:__init__:88 - index created!
2025-06-27 11:44:14.619 | INFO     | __main__:main:187 - loading checkpoint
2025-06-27 11:44:14.890 | INFO     | __main__:main:192 - loaded checkpoint done.
2025-06-27 11:44:14.890 | INFO     | __main__:main:198 - 	Fusing model...
2025-06-27 11:48:39.837 | INFO     | __main__:main:155 - Args: Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_rank=0, num_machines=1, machine_rank=0, exp_file='exps/example/mot/yolox_x_mix_det.py', fp16=True, fuse=True, trt=False, test=False, speed=False, opts=[], ckpt='pretrained/bytetrack_x_mot17.pth.tar', conf=0.01, nms=0.7, tsize=None, seed=None, track_thresh=0.6, track_buffer=30, match_thresh=0.9, min_box_area=100, mot20=False)
2025-06-27 11:48:40.231 | INFO     | __main__:main:165 - Model Summary: Params: 99.00M, Gflops: 793.21
2025-06-27 11:48:40.231 | INFO     | yolox.data.datasets.mot:__init__:39 - loading annotations into memory...
2025-06-27 11:48:40.508 | INFO     | yolox.data.datasets.mot:__init__:39 - Done (t=0.28s)
2025-06-27 11:48:40.508 | INFO     | pycocotools.coco:__init__:88 - creating index...
2025-06-27 11:48:40.525 | INFO     | pycocotools.coco:__init__:88 - index created!
2025-06-27 11:48:41.139 | INFO     | __main__:main:187 - loading checkpoint
2025-06-27 11:48:41.408 | INFO     | __main__:main:192 - loaded checkpoint done.
2025-06-27 11:48:41.408 | INFO     | __main__:main:198 - 	Fusing model...
2025-06-27 11:49:30.946 | INFO     | yolox.evaluators.mot_evaluator:write_results:39 - save results to ./YOLOX_outputs/yolox_x_mix_det/track_results/MOT17-02.txt
2025-06-27 11:52:14.260 | INFO     | __main__:main:155 - Args: Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_rank=0, num_machines=1, machine_rank=0, exp_file='exps/example/mot/yolox_x_mix_det.py', fp16=True, fuse=True, trt=False, test=False, speed=False, opts=[], ckpt='pretrained/bytetrack_x_mot17.pth.tar', conf=0.01, nms=0.7, tsize=None, seed=None, track_thresh=0.6, track_buffer=30, match_thresh=0.9, min_box_area=100, mot20=False)
2025-06-27 11:52:14.658 | INFO     | __main__:main:165 - Model Summary: Params: 99.00M, Gflops: 793.21
2025-06-27 11:52:14.658 | INFO     | yolox.data.datasets.mot:__init__:39 - loading annotations into memory...
2025-06-27 11:52:14.734 | INFO     | yolox.data.datasets.mot:__init__:39 - Done (t=0.08s)
2025-06-27 11:52:14.734 | INFO     | pycocotools.coco:__init__:88 - creating index...
2025-06-27 11:52:14.737 | INFO     | pycocotools.coco:__init__:88 - index created!
2025-06-27 11:52:14.755 | ERROR    | yolox.core.launch:launch:90 - An error has been caught in function 'launch', process 'MainProcess' (21360), thread 'MainThread' (140232909930624):
Traceback (most recent call last):

  File "/home/stas/ID-REID/ByteTrack/tools/track.py", line 287, in <module>
    launch(
    └ <function launch at 0x7f89c8464160>

> File "/home/stas/ID-REID/ByteTrack/yolox/core/launch.py", line 90, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x7f89760b05e0>

  File "/home/stas/ID-REID/ByteTrack/tools/track.py", line 168, in main
    val_loader = exp.get_eval_loader(args.batch_size, is_distributed, args.test)
                 │   │               │    │           │               │    └ False
                 │   │               │    │           │               └ Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_ra...
                 │   │               │    │           └ False
                 │   │               │    └ 1
                 │   │               └ Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_ra...
                 │   └ <function Exp.get_eval_loader at 0x7f89760b0ee0>
                 └ ╒══════════════════╤═════════════════════════════════════════════════════════════════════════════════════════════════════════...

  File "/home/stas/ID-REID/ByteTrack/exps/example/mot/yolox_x_mix_det.py", line 97, in get_eval_loader
    valdataset = MOTDataset(
                 └ <class 'yolox.data.datasets.mot.MOTDataset'>

  File "/home/stas/ID-REID/ByteTrack/yolox/data/datasets/mot.py", line 44, in __init__
    self.annotations = self._load_coco_annotations()
    │                  │    └ <function MOTDataset._load_coco_annotations at 0x7f89b7a589d0>
    │                  └ <yolox.data.datasets.mot.MOTDataset object at 0x7f89facd33a0>
    └ <yolox.data.datasets.mot.MOTDataset object at 0x7f89facd33a0>

  File "/home/stas/ID-REID/ByteTrack/yolox/data/datasets/mot.py", line 53, in _load_coco_annotations
    return [self.load_anno_from_ids(_ids) for _ids in self.ids]
            │    │                                    │    └ [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 3...
            │    │                                    └ <yolox.data.datasets.mot.MOTDataset object at 0x7f89facd33a0>
            │    └ <function MOTDataset.load_anno_from_ids at 0x7f89b7a58a60>
            └ <yolox.data.datasets.mot.MOTDataset object at 0x7f89facd33a0>

  File "/home/stas/ID-REID/ByteTrack/yolox/data/datasets/mot.py", line 53, in <listcomp>
    return [self.load_anno_from_ids(_ids) for _ids in self.ids]
            │    │                  │         │       │    └ [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 3...
            │    │                  │         │       └ <yolox.data.datasets.mot.MOTDataset object at 0x7f89facd33a0>
            │    │                  │         └ 1701
            │    │                  └ 1701
            │    └ <function MOTDataset.load_anno_from_ids at 0x7f89b7a58a60>
            └ <yolox.data.datasets.mot.MOTDataset object at 0x7f89facd33a0>

  File "/home/stas/ID-REID/ByteTrack/yolox/data/datasets/mot.py", line 78, in load_anno_from_ids
    cls = self.class_ids.index(obj["category_id"])
          │    │         │     └ {'id': 20410, 'category_id': -1, 'image_id': 1701, 'track_id': 1498, 'bbox': [683.0, 121.0, 22.64900016784668, 68.15200042724...
          │    │         └ <method 'index' of 'list' objects>
          │    └ [1]
          └ <yolox.data.datasets.mot.MOTDataset object at 0x7f89facd33a0>

ValueError: -1 is not in list
2025-06-27 11:54:17.441 | INFO     | __main__:main:155 - Args: Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_rank=0, num_machines=1, machine_rank=0, exp_file='exps/example/mot/yolox_x_mix_det.py', fp16=True, fuse=True, trt=False, test=False, speed=False, opts=[], ckpt='pretrained/bytetrack_x_mot17.pth.tar', conf=0.01, nms=0.7, tsize=None, seed=None, track_thresh=0.6, track_buffer=30, match_thresh=0.9, min_box_area=100, mot20=False)
2025-06-27 11:54:17.838 | INFO     | __main__:main:165 - Model Summary: Params: 99.00M, Gflops: 793.21
2025-06-27 11:54:17.838 | INFO     | yolox.data.datasets.mot:__init__:39 - loading annotations into memory...
2025-06-27 11:54:17.913 | INFO     | yolox.data.datasets.mot:__init__:39 - Done (t=0.07s)
2025-06-27 11:54:17.913 | INFO     | pycocotools.coco:__init__:88 - creating index...
2025-06-27 11:54:17.916 | INFO     | pycocotools.coco:__init__:88 - index created!
2025-06-27 11:54:17.933 | ERROR    | yolox.core.launch:launch:90 - An error has been caught in function 'launch', process 'MainProcess' (22420), thread 'MainThread' (140003596316800):
Traceback (most recent call last):

  File "/home/stas/ID-REID/ByteTrack/tools/track.py", line 287, in <module>
    launch(
    └ <function launch at 0x7f54641e3160>

> File "/home/stas/ID-REID/ByteTrack/yolox/core/launch.py", line 90, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x7f5411e2f5e0>

  File "/home/stas/ID-REID/ByteTrack/tools/track.py", line 168, in main
    val_loader = exp.get_eval_loader(args.batch_size, is_distributed, args.test)
                 │   │               │    │           │               │    └ False
                 │   │               │    │           │               └ Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_ra...
                 │   │               │    │           └ False
                 │   │               │    └ 1
                 │   │               └ Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_ra...
                 │   └ <function Exp.get_eval_loader at 0x7f5411e2fee0>
                 └ ╒══════════════════╤═════════════════════════════════════════════════════════════════════════════════════════════════════════...

  File "/home/stas/ID-REID/ByteTrack/exps/example/mot/yolox_x_mix_det.py", line 97, in get_eval_loader
    valdataset = MOTDataset(
                 └ <class 'yolox.data.datasets.mot.MOTDataset'>

  File "/home/stas/ID-REID/ByteTrack/yolox/data/datasets/mot.py", line 44, in __init__
    self.annotations = self._load_coco_annotations()
    │                  │    └ <function MOTDataset._load_coco_annotations at 0x7f54537d79d0>
    │                  └ <yolox.data.datasets.mot.MOTDataset object at 0x7f5498a523a0>
    └ <yolox.data.datasets.mot.MOTDataset object at 0x7f5498a523a0>

  File "/home/stas/ID-REID/ByteTrack/yolox/data/datasets/mot.py", line 53, in _load_coco_annotations
    return [self.load_anno_from_ids(_ids) for _ids in self.ids]
            │    │                                    │    └ [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 3...
            │    │                                    └ <yolox.data.datasets.mot.MOTDataset object at 0x7f5498a523a0>
            │    └ <function MOTDataset.load_anno_from_ids at 0x7f54537d7a60>
            └ <yolox.data.datasets.mot.MOTDataset object at 0x7f5498a523a0>

  File "/home/stas/ID-REID/ByteTrack/yolox/data/datasets/mot.py", line 53, in <listcomp>
    return [self.load_anno_from_ids(_ids) for _ids in self.ids]
            │    │                  │         │       │    └ [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 3...
            │    │                  │         │       └ <yolox.data.datasets.mot.MOTDataset object at 0x7f5498a523a0>
            │    │                  │         └ 1701
            │    │                  └ 1701
            │    └ <function MOTDataset.load_anno_from_ids at 0x7f54537d7a60>
            └ <yolox.data.datasets.mot.MOTDataset object at 0x7f5498a523a0>

  File "/home/stas/ID-REID/ByteTrack/yolox/data/datasets/mot.py", line 78, in load_anno_from_ids
    cls = self.class_ids.index(obj["category_id"])
          │    │         │     └ {'id': 20410, 'category_id': -1, 'image_id': 1701, 'track_id': 1498, 'bbox': [683.0, 121.0, 22.64900016784668, 68.15200042724...
          │    │         └ <method 'index' of 'list' objects>
          │    └ [1]
          └ <yolox.data.datasets.mot.MOTDataset object at 0x7f5498a523a0>

ValueError: -1 is not in list
2025-06-27 11:59:56.421 | INFO     | __main__:main:155 - Args: Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_rank=0, num_machines=1, machine_rank=0, exp_file='exps/example/mot/yolox_x_mix_det.py', fp16=True, fuse=True, trt=False, test=False, speed=False, opts=[], ckpt='pretrained/bytetrack_x_mot17.pth.tar', conf=0.01, nms=0.7, tsize=None, seed=None, track_thresh=0.6, track_buffer=30, match_thresh=0.9, min_box_area=100, mot20=False)
2025-06-27 11:59:56.819 | INFO     | __main__:main:165 - Model Summary: Params: 99.00M, Gflops: 793.21
2025-06-27 11:59:56.820 | INFO     | yolox.data.datasets.mot:__init__:39 - loading annotations into memory...
2025-06-27 11:59:56.895 | INFO     | yolox.data.datasets.mot:__init__:39 - Done (t=0.08s)
2025-06-27 11:59:56.895 | INFO     | pycocotools.coco:__init__:88 - creating index...
2025-06-27 11:59:56.898 | INFO     | pycocotools.coco:__init__:88 - index created!
2025-06-27 11:59:57.368 | INFO     | __main__:main:187 - loading checkpoint
2025-06-27 11:59:57.646 | INFO     | __main__:main:192 - loaded checkpoint done.
2025-06-27 11:59:57.647 | INFO     | __main__:main:198 - 	Fusing model...
2025-06-27 12:00:11.387 | INFO     | yolox.evaluators.mot_evaluator:write_results:39 - save results to ./YOLOX_outputs/yolox_x_mix_det/track_results/KITTI-17.txt
2025-06-27 12:00:50.703 | INFO     | yolox.evaluators.mot_evaluator:write_results:39 - save results to ./YOLOX_outputs/yolox_x_mix_det/track_results/MOT16-09.txt
2025-06-27 12:01:58.316 | INFO     | yolox.evaluators.mot_evaluator:write_results:39 - save results to ./YOLOX_outputs/yolox_x_mix_det/track_results/MOT16-11.txt
2025-06-27 12:02:58.769 | INFO     | yolox.evaluators.mot_evaluator:write_results:39 - save results to ./YOLOX_outputs/yolox_x_mix_det/track_results/PETS09-S2L1.txt
2025-06-27 12:03:04.249 | INFO     | yolox.evaluators.mot_evaluator:write_results:39 - save results to ./YOLOX_outputs/yolox_x_mix_det/track_results/TUD-Campus.txt
2025-06-27 12:03:18.271 | INFO     | yolox.evaluators.mot_evaluator:write_results:39 - save results to ./YOLOX_outputs/yolox_x_mix_det/track_results/TUD-Stadtmitte.txt
2025-06-27 12:03:18.306 | INFO     | yolox.evaluators.mot_evaluator:evaluate_prediction:628 - Evaluate in main process...
2025-06-27 12:03:18.827 | INFO     | yolox.evaluators.mot_evaluator:evaluate_prediction:657 - Loading and preparing results...
2025-06-27 12:03:18.942 | INFO     | yolox.evaluators.mot_evaluator:evaluate_prediction:657 - DONE (t=0.11s)
2025-06-27 12:03:18.943 | INFO     | pycocotools.coco:loadRes:363 - creating index...
2025-06-27 12:03:18.948 | INFO     | pycocotools.coco:loadRes:363 - index created!
2025-06-27 12:03:19.207 | INFO     | __main__:main:219 - 
Average forward time: 73.83 ms, Average track time: 1.17 ms, Average inference time: 75.01 ms
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.596
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.924
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.601
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.002
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.408
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.724
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.091
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.671
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.710
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.300
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.545
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.804

2025-06-27 12:03:19.208 | INFO     | __main__:main:237 - Found 6 groundtruths and 7 test files.
2025-06-27 12:03:19.208 | INFO     | __main__:main:238 - Available LAP solvers ['lap', 'scipy']
2025-06-27 12:03:19.208 | INFO     | __main__:main:239 - Default LAP solver 'lap'
2025-06-27 12:03:19.208 | INFO     | __main__:main:240 - Loading files.
2025-06-27 12:03:19.495 | INFO     | __main__:compare_dataframes:118 - Comparing TUD-Stadtmitte...
2025-06-27 12:03:19.536 | INFO     | __main__:compare_dataframes:118 - Comparing TUD-Campus...
2025-06-27 12:03:19.553 | WARNING  | __main__:compare_dataframes:122 - No ground truth for MOT17-02, skipping.
2025-06-27 12:03:19.553 | INFO     | __main__:compare_dataframes:118 - Comparing KITTI-17...
2025-06-27 12:03:19.585 | INFO     | __main__:compare_dataframes:118 - Comparing MOT16-11...
2025-06-27 12:03:19.795 | INFO     | __main__:compare_dataframes:118 - Comparing MOT16-09...
2025-06-27 12:03:19.960 | INFO     | __main__:compare_dataframes:118 - Comparing PETS09-S2L1...
2025-06-27 12:03:20.126 | INFO     | __main__:main:248 - Running metrics
2025-06-27 12:03:20.373 | INFO     | __main__:main:273 - Completed
2025-06-27 12:06:20.989 | INFO     | __main__:main:156 - Args: Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_rank=0, num_machines=1, machine_rank=0, exp_file='exps/example/mot/yolox_x_mix_det.py', fp16=True, fuse=True, trt=False, test=False, speed=False, opts=[], ckpt='pretrained/bytetrack_x_mot17.pth.tar', conf=0.1, nms=0.7, tsize=None, seed=None, track_thresh=0.5, track_buffer=30, match_thresh=0.9, min_box_area=100, model_folder='pretrained/ckpt.t7')
2025-06-27 12:06:21.386 | INFO     | __main__:main:166 - Model Summary: Params: 99.00M, Gflops: 793.21
2025-06-27 12:06:21.387 | INFO     | yolox.data.datasets.mot:__init__:39 - loading annotations into memory...
2025-06-27 12:06:21.461 | INFO     | yolox.data.datasets.mot:__init__:39 - Done (t=0.07s)
2025-06-27 12:06:21.461 | INFO     | pycocotools.coco:__init__:88 - creating index...
2025-06-27 12:06:21.465 | INFO     | pycocotools.coco:__init__:88 - index created!
2025-06-27 12:06:21.950 | INFO     | __main__:main:190 - loading checkpoint
2025-06-27 12:06:22.226 | INFO     | __main__:main:195 - loaded checkpoint done.
2025-06-27 12:06:22.227 | INFO     | __main__:main:201 - 	Fusing model...
2025-06-27 12:06:22.835 | ERROR    | yolox.core.launch:launch:90 - An error has been caught in function 'launch', process 'MainProcess' (28639), thread 'MainThread' (140040929521792):
Traceback (most recent call last):

  File "/home/stas/ID-REID/ByteTrack/tools/track_deepsort.py", line 285, in <module>
    launch(
    └ <function launch at 0x7f5d15595f70>

> File "/home/stas/ID-REID/ByteTrack/yolox/core/launch.py", line 90, in launch
    main_func(*args)
    │          └ (╒══════════════════╤══════════════════════════════════════════════════════════════════════════════════════════════╕
    │            │ keys  ...
    └ <function main at 0x7f5cc31e9430>

  File "/home/stas/ID-REID/ByteTrack/tools/track_deepsort.py", line 219, in main
    *_, summary = evaluator.evaluate_deepsort(
                  │         └ <function MOTEvaluator.evaluate_deepsort at 0x7f5cc5a6a820>
                  └ <yolox.evaluators.mot_evaluator.MOTEvaluator object at 0x7f5d49e9d070>

  File "/home/stas/ID-REID/ByteTrack/yolox/evaluators/mot_evaluator.py", line 395, in evaluate_deepsort
    tracker = DeepSort(model_folder, min_confidence=self.args.track_thresh)
              │        │                            │    │    └ 0.5
              │        │                            │    └ Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_ra...
              │        │                            └ <yolox.evaluators.mot_evaluator.MOTEvaluator object at 0x7f5d49e9d070>
              │        └ 'pretrained/ckpt.t7'
              └ <class 'yolox.deepsort_tracker.deepsort.DeepSort'>

  File "/home/stas/ID-REID/ByteTrack/yolox/deepsort_tracker/deepsort.py", line 160, in __init__
    self.extractor = Extractor(model_path, use_cuda=use_cuda)
    │                │         │                    └ True
    │                │         └ 'pretrained/ckpt.t7'
    │                └ <class 'yolox.deepsort_tracker.reid_model.Extractor'>
    └ <yolox.deepsort_tracker.deepsort.DeepSort object at 0x7f5d4cfae070>

  File "/home/stas/ID-REID/ByteTrack/yolox/deepsort_tracker/reid_model.py", line 112, in __init__
    state_dict = torch.load(model_path, map_location=torch.device(self.device))[
                 │     │    │                        │     │      │    └ 'cuda'
                 │     │    │                        │     │      └ <yolox.deepsort_tracker.reid_model.Extractor object at 0x7f5d4cfaea00>
                 │     │    │                        │     └ <class 'torch.device'>
                 │     │    │                        └ <module 'torch' from '/home/stas/ID-REID/ByteTrack/.venv/lib/python3.9/site-packages/torch/__init__.py'>
                 │     │    └ 'pretrained/ckpt.t7'
                 │     └ <function load at 0x7f5d17202ee0>
                 └ <module 'torch' from '/home/stas/ID-REID/ByteTrack/.venv/lib/python3.9/site-packages/torch/__init__.py'>

  File "/home/stas/ID-REID/ByteTrack/.venv/lib/python3.9/site-packages/torch/serialization.py", line 771, in load
    with _open_file_like(f, 'rb') as opened_file:
         │               └ 'pretrained/ckpt.t7'
         └ <function _open_file_like at 0x7f5d17202310>
  File "/home/stas/ID-REID/ByteTrack/.venv/lib/python3.9/site-packages/torch/serialization.py", line 270, in _open_file_like
    return _open_file(name_or_buffer, mode)
           │          │               └ 'rb'
           │          └ 'pretrained/ckpt.t7'
           └ <class 'torch.serialization._open_file'>
  File "/home/stas/ID-REID/ByteTrack/.venv/lib/python3.9/site-packages/torch/serialization.py", line 251, in __init__
    super(_open_file, self).__init__(open(name, mode))
          │           │                   │     └ 'rb'
          │           │                   └ 'pretrained/ckpt.t7'
          │           └ <torch.serialization._open_file object at 0x7f5d506468b0>
          └ <class 'torch.serialization._open_file'>

FileNotFoundError: [Errno 2] No such file or directory: 'pretrained/ckpt.t7'
2025-06-27 12:08:04.305 | INFO     | __main__:main:156 - Args: Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_rank=0, num_machines=1, machine_rank=0, exp_file='exps/example/mot/yolox_x_mix_det.py', fp16=True, fuse=True, trt=False, test=False, speed=False, opts=[], ckpt='pretrained/bytetrack_x_mot17.pth.tar', conf=0.1, nms=0.7, tsize=None, seed=None, track_thresh=0.5, track_buffer=30, match_thresh=0.9, min_box_area=100, model_folder='pretrained/ckpt.t7')
2025-06-27 12:08:04.708 | INFO     | __main__:main:166 - Model Summary: Params: 99.00M, Gflops: 793.21
2025-06-27 12:08:04.709 | INFO     | yolox.data.datasets.mot:__init__:39 - loading annotations into memory...
2025-06-27 12:08:04.784 | INFO     | yolox.data.datasets.mot:__init__:39 - Done (t=0.08s)
2025-06-27 12:08:04.784 | INFO     | pycocotools.coco:__init__:88 - creating index...
2025-06-27 12:08:04.788 | INFO     | pycocotools.coco:__init__:88 - index created!
2025-06-27 12:08:05.275 | INFO     | __main__:main:190 - loading checkpoint
2025-06-27 12:08:05.543 | INFO     | __main__:main:195 - loaded checkpoint done.
2025-06-27 12:08:05.543 | INFO     | __main__:main:201 - 	Fusing model...
2025-06-27 12:08:06.140 | ERROR    | yolox.core.launch:launch:90 - An error has been caught in function 'launch', process 'MainProcess' (29547), thread 'MainThread' (139914272784512):
Traceback (most recent call last):

  File "/home/stas/ID-REID/ByteTrack/tools/track_deepsort.py", line 285, in <module>
    launch(
    └ <function launch at 0x7f3f9804df70>

> File "/home/stas/ID-REID/ByteTrack/yolox/core/launch.py", line 90, in launch
    main_func(*args)
    │          └ (╒══════════════════╤══════════════════════════════════════════════════════════════════════════════════════════════╕
    │            │ keys  ...
    └ <function main at 0x7f3f45ca1430>

  File "/home/stas/ID-REID/ByteTrack/tools/track_deepsort.py", line 219, in main
    *_, summary = evaluator.evaluate_deepsort(
                  │         └ <function MOTEvaluator.evaluate_deepsort at 0x7f3f485a0820>
                  └ <yolox.evaluators.mot_evaluator.MOTEvaluator object at 0x7f3fbf0d0160>

  File "/home/stas/ID-REID/ByteTrack/yolox/evaluators/mot_evaluator.py", line 395, in evaluate_deepsort
    tracker = DeepSort(model_folder, min_confidence=self.args.track_thresh)
              │        │                            │    │    └ 0.5
              │        │                            │    └ Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_ra...
              │        │                            └ <yolox.evaluators.mot_evaluator.MOTEvaluator object at 0x7f3fbf0d0160>
              │        └ 'pretrained/ckpt.t7'
              └ <class 'yolox.deepsort_tracker.deepsort.DeepSort'>

  File "/home/stas/ID-REID/ByteTrack/yolox/deepsort_tracker/deepsort.py", line 160, in __init__
    self.extractor = Extractor(model_path, use_cuda=use_cuda)
    │                │         │                    └ True
    │                │         └ 'pretrained/ckpt.t7'
    │                └ <class 'yolox.deepsort_tracker.reid_model.Extractor'>
    └ <yolox.deepsort_tracker.deepsort.DeepSort object at 0x7f3fca91b070>

  File "/home/stas/ID-REID/ByteTrack/yolox/deepsort_tracker/reid_model.py", line 114, in __init__
    self.net.load_state_dict(state_dict)
    │    │   │               └ OrderedDict([('conv.0.weight', tensor([[[[-2.3999e-02, -2.6633e-02,  5.5990e-03],
    │    │   │                           [ 3.7733e-03,  1.1084e-02,  4.763...
    │    │   └ <function Module.load_state_dict at 0x7f3f99b3c0d0>
    │    └ Net(
    │        (conv): Sequential(
    │          (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    │          (1): BatchNorm2d(64,...
    └ <yolox.deepsort_tracker.reid_model.Extractor object at 0x7f3fca91ba00>

  File "/home/stas/ID-REID/ByteTrack/.venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(

RuntimeError: Error(s) in loading state_dict for Net:
	Missing key(s) in state_dict: "layer4.0.conv1.weight", "layer4.0.bn1.weight", "layer4.0.bn1.bias", "layer4.0.bn1.running_mean", "layer4.0.bn1.running_var", "layer4.0.conv2.weight", "layer4.0.bn2.weight", "layer4.0.bn2.bias", "layer4.0.bn2.running_mean", "layer4.0.bn2.running_var", "layer4.0.downsample.0.weight", "layer4.0.downsample.1.weight", "layer4.0.downsample.1.bias", "layer4.0.downsample.1.running_mean", "layer4.0.downsample.1.running_var", "layer4.1.conv1.weight", "layer4.1.bn1.weight", "layer4.1.bn1.bias", "layer4.1.bn1.running_mean", "layer4.1.bn1.running_var", "layer4.1.conv2.weight", "layer4.1.bn2.weight", "layer4.1.bn2.bias", "layer4.1.bn2.running_mean", "layer4.1.bn2.running_var", "classifier.1.weight", "classifier.1.bias", "classifier.1.running_mean", "classifier.1.running_var", "classifier.4.weight", "classifier.4.bias". 
	Unexpected key(s) in state_dict: "dense.1.weight", "dense.1.bias", "dense.2.weight", "dense.2.bias", "dense.2.running_mean", "dense.2.running_var", "batch_norm.weight", "batch_norm.bias", "batch_norm.running_mean", "batch_norm.running_var", "conv.4.weight", "conv.4.bias", "conv.4.running_mean", "conv.4.running_var", "conv.3.weight", "conv.3.bias". 
	size mismatch for conv.0.weight: copying a param with shape torch.Size([32, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 3, 3, 3]).
	size mismatch for conv.0.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for conv.1.weight: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for conv.1.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for conv.1.running_mean: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for conv.1.running_var: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for layer1.0.conv1.weight: copying a param with shape torch.Size([32, 32, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
	size mismatch for layer1.0.bn1.weight: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for layer1.0.bn1.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for layer1.0.bn1.running_mean: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for layer1.0.bn1.running_var: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for layer1.0.conv2.weight: copying a param with shape torch.Size([32, 32, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
	size mismatch for layer1.0.bn2.weight: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for layer1.0.bn2.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for layer1.0.bn2.running_mean: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for layer1.0.bn2.running_var: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for layer1.1.conv1.weight: copying a param with shape torch.Size([32, 32, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
	size mismatch for layer1.1.bn1.weight: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for layer1.1.bn1.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for layer1.1.bn1.running_mean: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for layer1.1.bn1.running_var: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for layer1.1.conv2.weight: copying a param with shape torch.Size([32, 32, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
	size mismatch for layer1.1.bn2.weight: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for layer1.1.bn2.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for layer1.1.bn2.running_mean: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for layer1.1.bn2.running_var: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for layer2.0.conv1.weight: copying a param with shape torch.Size([64, 32, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 64, 3, 3]).
	size mismatch for layer2.0.bn1.weight: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for layer2.0.bn1.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for layer2.0.bn1.running_mean: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for layer2.0.bn1.running_var: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for layer2.0.conv2.weight: copying a param with shape torch.Size([64, 64, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 128, 3, 3]).
	size mismatch for layer2.0.bn2.weight: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for layer2.0.bn2.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for layer2.0.bn2.running_mean: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for layer2.0.bn2.running_var: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for layer2.0.downsample.0.weight: copying a param with shape torch.Size([64, 32, 1, 1]) from checkpoint, the shape in current model is torch.Size([128, 64, 1, 1]).
	size mismatch for layer2.0.downsample.1.weight: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for layer2.0.downsample.1.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for layer2.0.downsample.1.running_mean: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for layer2.0.downsample.1.running_var: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for layer2.1.conv1.weight: copying a param with shape torch.Size([64, 64, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 128, 3, 3]).
	size mismatch for layer2.1.bn1.weight: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for layer2.1.bn1.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for layer2.1.bn1.running_mean: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for layer2.1.bn1.running_var: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for layer2.1.conv2.weight: copying a param with shape torch.Size([64, 64, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 128, 3, 3]).
	size mismatch for layer2.1.bn2.weight: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for layer2.1.bn2.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for layer2.1.bn2.running_mean: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for layer2.1.bn2.running_var: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for layer3.0.conv1.weight: copying a param with shape torch.Size([128, 64, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 128, 3, 3]).
	size mismatch for layer3.0.bn1.weight: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for layer3.0.bn1.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for layer3.0.bn1.running_mean: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for layer3.0.bn1.running_var: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for layer3.0.conv2.weight: copying a param with shape torch.Size([128, 128, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3]).
	size mismatch for layer3.0.bn2.weight: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for layer3.0.bn2.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for layer3.0.bn2.running_mean: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for layer3.0.bn2.running_var: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for layer3.0.downsample.0.weight: copying a param with shape torch.Size([128, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([256, 128, 1, 1]).
	size mismatch for layer3.0.downsample.1.weight: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for layer3.0.downsample.1.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for layer3.0.downsample.1.running_mean: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for layer3.0.downsample.1.running_var: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for layer3.1.conv1.weight: copying a param with shape torch.Size([128, 128, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3]).
	size mismatch for layer3.1.bn1.weight: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for layer3.1.bn1.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for layer3.1.bn1.running_mean: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for layer3.1.bn1.running_var: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for layer3.1.conv2.weight: copying a param with shape torch.Size([128, 128, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3]).
	size mismatch for layer3.1.bn2.weight: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for layer3.1.bn2.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for layer3.1.bn2.running_mean: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for layer3.1.bn2.running_var: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for classifier.0.weight: copying a param with shape torch.Size([625, 128]) from checkpoint, the shape in current model is torch.Size([256, 512]).
	size mismatch for classifier.0.bias: copying a param with shape torch.Size([625]) from checkpoint, the shape in current model is torch.Size([256]).
2025-06-27 12:19:22.502 | INFO     | __main__:main:156 - Args: Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_rank=0, num_machines=1, machine_rank=0, exp_file='exps/example/mot/yolox_x_mix_det.py', fp16=True, fuse=True, trt=False, test=False, speed=False, opts=[], ckpt='pretrained/bytetrack_x_mot17.pth.tar', conf=0.1, nms=0.7, tsize=None, seed=None, track_thresh=0.5, track_buffer=30, match_thresh=0.9, min_box_area=100, model_folder='pretrained/ckpt.t7')
2025-06-27 12:19:22.911 | INFO     | __main__:main:166 - Model Summary: Params: 99.00M, Gflops: 793.21
2025-06-27 12:19:22.911 | INFO     | yolox.data.datasets.mot:__init__:39 - loading annotations into memory...
2025-06-27 12:19:22.986 | INFO     | yolox.data.datasets.mot:__init__:39 - Done (t=0.07s)
2025-06-27 12:19:22.986 | INFO     | pycocotools.coco:__init__:88 - creating index...
2025-06-27 12:19:22.989 | INFO     | pycocotools.coco:__init__:88 - index created!
2025-06-27 12:19:23.463 | INFO     | __main__:main:190 - loading checkpoint
2025-06-27 12:19:23.732 | INFO     | __main__:main:195 - loaded checkpoint done.
2025-06-27 12:19:23.732 | INFO     | __main__:main:201 - 	Fusing model...
2025-06-27 12:19:26.593 | ERROR    | yolox.core.launch:launch:90 - An error has been caught in function 'launch', process 'MainProcess' (3641), thread 'MainThread' (139818470568064):
Traceback (most recent call last):

  File "/home/stas/ID-REID/ByteTrack/tools/track_deepsort.py", line 285, in <module>
    launch(
    └ <function launch at 0x7f2949c31f70>

> File "/home/stas/ID-REID/ByteTrack/yolox/core/launch.py", line 90, in launch
    main_func(*args)
    │          └ (╒══════════════════╤══════════════════════════════════════════════════════════════════════════════════════════════╕
    │            │ keys  ...
    └ <function main at 0x7f28f7885430>

  File "/home/stas/ID-REID/ByteTrack/tools/track_deepsort.py", line 219, in main
    *_, summary = evaluator.evaluate_deepsort(
                  │         └ <function MOTEvaluator.evaluate_deepsort at 0x7f28fa183820>
                  └ <yolox.evaluators.mot_evaluator.MOTEvaluator object at 0x7f296a6a7190>

  File "/home/stas/ID-REID/ByteTrack/yolox/evaluators/mot_evaluator.py", line 437, in evaluate_deepsort
    online_targets = tracker.update(outputs[0], info_imgs, self.img_size, img_file_name[0])
                     │       │      │           │          │    │         └ ['KITTI-17/img1/000001.jpg']
                     │       │      │           │          │    └ (800, 1440)
                     │       │      │           │          └ <yolox.evaluators.mot_evaluator.MOTEvaluator object at 0x7f296a6a7190>
                     │       │      │           └ [tensor([370]), tensor([1224]), tensor([1]), tensor([1]), ['KITTI-17/img1/000001.jpg']]
                     │       │      └ [tensor([[4.4650e+02, 1.8025e+02, 5.8650e+02, 4.2375e+02, 9.9805e-01, 9.4434e-01,
                     │       │                 0.0000e+00],
                     │       │                [5.2800e+02, ...
                     │       └ <function DeepSort.update at 0x7f28fa173a60>
                     └ <yolox.deepsort_tracker.deepsort.DeepSort object at 0x7f298596e070>

  File "/home/stas/ID-REID/ByteTrack/yolox/deepsort_tracker/deepsort.py", line 171, in update
    self.height, self.width = ori_img.shape[:2]
    │            │            └ None
    │            └ <yolox.deepsort_tracker.deepsort.DeepSort object at 0x7f298596e070>
    └ <yolox.deepsort_tracker.deepsort.DeepSort object at 0x7f298596e070>

AttributeError: 'NoneType' object has no attribute 'shape'
2025-06-27 12:20:39.795 | INFO     | __main__:main:156 - Args: Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_rank=0, num_machines=1, machine_rank=0, exp_file='exps/example/mot/yolox_x_mix_det.py', fp16=True, fuse=True, trt=False, test=False, speed=False, opts=[], ckpt='pretrained/bytetrack_x_mot17.pth.tar', conf=0.1, nms=0.7, tsize=None, seed=None, track_thresh=0.5, track_buffer=30, match_thresh=0.9, min_box_area=100, model_folder='pretrained/ckpt.t7')
2025-06-27 12:20:40.190 | INFO     | __main__:main:166 - Model Summary: Params: 99.00M, Gflops: 793.21
2025-06-27 12:20:40.190 | INFO     | yolox.data.datasets.mot:__init__:39 - loading annotations into memory...
2025-06-27 12:20:40.265 | INFO     | yolox.data.datasets.mot:__init__:39 - Done (t=0.07s)
2025-06-27 12:20:40.265 | INFO     | pycocotools.coco:__init__:88 - creating index...
2025-06-27 12:20:40.268 | INFO     | pycocotools.coco:__init__:88 - index created!
2025-06-27 12:20:40.751 | INFO     | __main__:main:190 - loading checkpoint
2025-06-27 12:20:41.021 | INFO     | __main__:main:195 - loaded checkpoint done.
2025-06-27 12:20:41.021 | INFO     | __main__:main:201 - 	Fusing model...
2025-06-27 12:21:00.802 | INFO     | yolox.evaluators.mot_evaluator:write_results_no_score:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/track_results_deepsort/KITTI-17.txt
2025-06-27 12:22:12.571 | INFO     | yolox.evaluators.mot_evaluator:write_results_no_score:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/track_results_deepsort/MOT16-09.txt
2025-06-27 12:24:25.482 | INFO     | yolox.evaluators.mot_evaluator:write_results_no_score:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/track_results_deepsort/MOT16-11.txt
2025-06-27 12:25:51.742 | INFO     | yolox.evaluators.mot_evaluator:write_results_no_score:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/track_results_deepsort/PETS09-S2L1.txt
2025-06-27 12:25:58.247 | INFO     | yolox.evaluators.mot_evaluator:write_results_no_score:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/track_results_deepsort/TUD-Campus.txt
2025-06-27 12:26:16.196 | INFO     | yolox.evaluators.mot_evaluator:write_results_no_score:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/track_results_deepsort/TUD-Stadtmitte.txt
2025-06-27 12:26:16.272 | INFO     | yolox.evaluators.mot_evaluator:evaluate_prediction:628 - Evaluate in main process...
2025-06-27 12:26:16.571 | INFO     | yolox.evaluators.mot_evaluator:evaluate_prediction:657 - Loading and preparing results...
2025-06-27 12:26:16.660 | INFO     | yolox.evaluators.mot_evaluator:evaluate_prediction:657 - DONE (t=0.09s)
2025-06-27 12:26:16.660 | INFO     | pycocotools.coco:loadRes:363 - creating index...
2025-06-27 12:26:16.664 | INFO     | pycocotools.coco:loadRes:363 - index created!
2025-06-27 12:26:16.832 | INFO     | __main__:main:222 - 
Average forward time: 75.19 ms, Average track time: 38.83 ms, Average inference time: 114.02 ms
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.593
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.917
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.596
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.002
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.405
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.719
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.091
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.670
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.704
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.300
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.539
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.798

2025-06-27 12:26:16.833 | INFO     | __main__:main:235 - Found 7 groundtruths and 6 test files.
2025-06-27 12:26:16.833 | INFO     | __main__:main:236 - Available LAP solvers ['lap', 'scipy']
2025-06-27 12:26:16.833 | INFO     | __main__:main:237 - Default LAP solver 'lap'
2025-06-27 12:26:16.833 | INFO     | __main__:main:238 - Loading files.
2025-06-27 12:26:17.381 | WARNING  | __main__:compare_dataframes:123 - No ground truth for TUD-Stadtmitte, skipping.
2025-06-27 12:26:17.381 | WARNING  | __main__:compare_dataframes:123 - No ground truth for TUD-Campus, skipping.
2025-06-27 12:26:17.381 | WARNING  | __main__:compare_dataframes:123 - No ground truth for KITTI-17, skipping.
2025-06-27 12:26:17.381 | WARNING  | __main__:compare_dataframes:123 - No ground truth for MOT16-11, skipping.
2025-06-27 12:26:17.381 | WARNING  | __main__:compare_dataframes:123 - No ground truth for MOT16-09, skipping.
2025-06-27 12:26:17.381 | WARNING  | __main__:compare_dataframes:123 - No ground truth for PETS09-S2L1, skipping.
2025-06-27 12:26:17.382 | INFO     | __main__:main:246 - Running metrics
2025-06-27 12:26:17.386 | INFO     | __main__:main:271 - Completed
2025-06-27 12:29:26.398 | INFO     | __main__:main:156 - Args: Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_rank=0, num_machines=1, machine_rank=0, exp_file='exps/example/mot/yolox_x_mix_det.py', fp16=True, fuse=True, trt=False, test=False, speed=False, opts=[], ckpt='pretrained/bytetrack_x_mot17.pth.tar', conf=0.1, nms=0.7, tsize=None, seed=None, track_thresh=0.5, track_buffer=30, match_thresh=0.9, min_box_area=100, model_folder='pretrained/ckpt.t7')
2025-06-27 12:29:26.798 | INFO     | __main__:main:166 - Model Summary: Params: 99.00M, Gflops: 793.21
2025-06-27 12:29:26.798 | INFO     | yolox.data.datasets.mot:__init__:39 - loading annotations into memory...
2025-06-27 12:29:26.874 | INFO     | yolox.data.datasets.mot:__init__:39 - Done (t=0.08s)
2025-06-27 12:29:26.874 | INFO     | pycocotools.coco:__init__:88 - creating index...
2025-06-27 12:29:26.878 | INFO     | pycocotools.coco:__init__:88 - index created!
2025-06-27 12:29:27.356 | INFO     | __main__:main:190 - loading checkpoint
2025-06-27 12:29:27.633 | INFO     | __main__:main:195 - loaded checkpoint done.
2025-06-27 12:29:27.633 | INFO     | __main__:main:201 - 	Fusing model...
2025-06-27 12:29:47.580 | INFO     | yolox.evaluators.mot_evaluator:write_results_no_score:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/track_results_deepsort/KITTI-17.txt
2025-06-27 12:31:01.889 | INFO     | yolox.evaluators.mot_evaluator:write_results_no_score:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/track_results_deepsort/MOT16-09.txt
2025-06-27 12:33:15.327 | INFO     | yolox.evaluators.mot_evaluator:write_results_no_score:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/track_results_deepsort/MOT16-11.txt
2025-06-27 12:34:40.533 | INFO     | yolox.evaluators.mot_evaluator:write_results_no_score:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/track_results_deepsort/PETS09-S2L1.txt
2025-06-27 12:34:46.914 | INFO     | yolox.evaluators.mot_evaluator:write_results_no_score:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/track_results_deepsort/TUD-Campus.txt
2025-06-27 12:35:04.611 | INFO     | yolox.evaluators.mot_evaluator:write_results_no_score:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/track_results_deepsort/TUD-Stadtmitte.txt
2025-06-27 12:35:04.666 | INFO     | yolox.evaluators.mot_evaluator:evaluate_prediction:628 - Evaluate in main process...
2025-06-27 12:35:04.836 | INFO     | yolox.evaluators.mot_evaluator:evaluate_prediction:657 - Loading and preparing results...
2025-06-27 12:35:04.923 | INFO     | yolox.evaluators.mot_evaluator:evaluate_prediction:657 - DONE (t=0.09s)
2025-06-27 12:35:04.924 | INFO     | pycocotools.coco:loadRes:363 - creating index...
2025-06-27 12:35:04.928 | INFO     | pycocotools.coco:loadRes:363 - index created!
2025-06-27 12:35:05.096 | INFO     | __main__:main:222 - 
Average forward time: 76.84 ms, Average track time: 37.81 ms, Average inference time: 114.64 ms
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.592
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.917
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.596
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.002
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.405
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.719
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.091
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.670
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.704
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.300
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.539
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.798

2025-06-27 12:35:05.096 | INFO     | __main__:main:235 - Found 0 groundtruths and 6 test files.
2025-06-27 12:35:05.096 | INFO     | __main__:main:236 - Available LAP solvers ['lap', 'scipy']
2025-06-27 12:35:05.096 | INFO     | __main__:main:237 - Default LAP solver 'lap'
2025-06-27 12:35:05.096 | INFO     | __main__:main:238 - Loading files.
2025-06-27 12:35:05.198 | WARNING  | __main__:compare_dataframes:123 - No ground truth for TUD-Stadtmitte, skipping.
2025-06-27 12:35:05.198 | WARNING  | __main__:compare_dataframes:123 - No ground truth for TUD-Campus, skipping.
2025-06-27 12:35:05.198 | WARNING  | __main__:compare_dataframes:123 - No ground truth for KITTI-17, skipping.
2025-06-27 12:35:05.198 | WARNING  | __main__:compare_dataframes:123 - No ground truth for MOT16-11, skipping.
2025-06-27 12:35:05.198 | WARNING  | __main__:compare_dataframes:123 - No ground truth for MOT16-09, skipping.
2025-06-27 12:35:05.198 | WARNING  | __main__:compare_dataframes:123 - No ground truth for PETS09-S2L1, skipping.
2025-06-27 12:35:05.198 | INFO     | __main__:main:246 - Running metrics
2025-06-27 12:35:05.202 | INFO     | __main__:main:271 - Completed
2025-06-27 12:47:36.369 | INFO     | __main__:main:156 - Args: Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_rank=0, num_machines=1, machine_rank=0, exp_file='exps/example/mot/yolox_x_mix_det.py', fp16=True, fuse=True, trt=False, test=False, speed=False, opts=[], ckpt='pretrained/bytetrack_x_mot17.pth.tar', conf=0.1, nms=0.7, tsize=None, seed=None, track_thresh=0.5, track_buffer=30, match_thresh=0.9, min_box_area=100, model_folder='pretrained/ckpt.t7')
2025-06-27 12:47:36.767 | INFO     | __main__:main:166 - Model Summary: Params: 99.00M, Gflops: 793.21
2025-06-27 12:47:36.767 | INFO     | yolox.data.datasets.mot:__init__:39 - loading annotations into memory...
2025-06-27 12:47:36.843 | INFO     | yolox.data.datasets.mot:__init__:39 - Done (t=0.08s)
2025-06-27 12:47:36.843 | INFO     | pycocotools.coco:__init__:88 - creating index...
2025-06-27 12:47:36.846 | INFO     | pycocotools.coco:__init__:88 - index created!
2025-06-27 12:47:37.326 | INFO     | __main__:main:190 - loading checkpoint
2025-06-27 12:47:37.602 | INFO     | __main__:main:195 - loaded checkpoint done.
2025-06-27 12:47:37.602 | INFO     | __main__:main:201 - 	Fusing model...
2025-06-27 12:47:57.052 | INFO     | yolox.evaluators.mot_evaluator:write_results_no_score:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/track_results_deepsort/KITTI-17.txt
2025-06-27 12:49:10.727 | INFO     | yolox.evaluators.mot_evaluator:write_results_no_score:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/track_results_deepsort/MOT16-09.txt
2025-06-27 12:51:22.850 | INFO     | yolox.evaluators.mot_evaluator:write_results_no_score:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/track_results_deepsort/MOT16-11.txt
2025-06-27 12:52:48.864 | INFO     | yolox.evaluators.mot_evaluator:write_results_no_score:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/track_results_deepsort/PETS09-S2L1.txt
2025-06-27 12:52:55.274 | INFO     | yolox.evaluators.mot_evaluator:write_results_no_score:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/track_results_deepsort/TUD-Campus.txt
2025-06-27 12:53:12.969 | INFO     | yolox.evaluators.mot_evaluator:write_results_no_score:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/track_results_deepsort/TUD-Stadtmitte.txt
2025-06-27 12:53:13.037 | INFO     | yolox.evaluators.mot_evaluator:evaluate_prediction:628 - Evaluate in main process...
2025-06-27 12:53:13.307 | INFO     | yolox.evaluators.mot_evaluator:evaluate_prediction:657 - Loading and preparing results...
2025-06-27 12:53:13.397 | INFO     | yolox.evaluators.mot_evaluator:evaluate_prediction:657 - DONE (t=0.09s)
2025-06-27 12:53:13.397 | INFO     | pycocotools.coco:loadRes:363 - creating index...
2025-06-27 12:53:13.401 | INFO     | pycocotools.coco:loadRes:363 - index created!
2025-06-27 12:53:13.568 | INFO     | __main__:main:222 - 
Average forward time: 75.53 ms, Average track time: 38.71 ms, Average inference time: 114.23 ms
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.593
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.917
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.596
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.002
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.405
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.719
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.091
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.670
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.704
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.300
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.539
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.798

2025-06-27 12:53:13.568 | INFO     | __main__:main:235 - Found 6 groundtruths and 6 test files.
2025-06-27 12:53:13.568 | INFO     | __main__:main:236 - Available LAP solvers ['lap', 'scipy']
2025-06-27 12:53:13.568 | INFO     | __main__:main:237 - Default LAP solver 'lap'
2025-06-27 12:53:13.568 | INFO     | __main__:main:238 - Loading files.
2025-06-27 12:53:13.824 | INFO     | __main__:compare_dataframes:119 - Comparing TUD-Stadtmitte...
2025-06-27 12:53:13.865 | INFO     | __main__:compare_dataframes:119 - Comparing TUD-Campus...
2025-06-27 12:53:13.882 | INFO     | __main__:compare_dataframes:119 - Comparing KITTI-17...
2025-06-27 12:53:13.915 | INFO     | __main__:compare_dataframes:119 - Comparing MOT16-11...
2025-06-27 12:53:14.178 | INFO     | __main__:compare_dataframes:119 - Comparing MOT16-09...
2025-06-27 12:53:14.303 | INFO     | __main__:compare_dataframes:119 - Comparing PETS09-S2L1...
2025-06-27 12:53:14.518 | INFO     | __main__:main:246 - Running metrics
2025-06-27 12:53:14.774 | INFO     | __main__:main:271 - Completed
2025-06-27 12:58:58.783 | INFO     | __main__:main:156 - Args: Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_rank=0, num_machines=1, machine_rank=0, exp_file='exps/example/mot/yolox_x_mix_det.py', fp16=True, fuse=True, trt=False, test=False, speed=False, opts=[], ckpt='pretrained/bytetrack_x_mot17.pth.tar', conf=0.1, nms=0.7, tsize=None, seed=None, track_thresh=0.6, track_buffer=30, match_thresh=0.9, min_box_area=100, model_folder='pretrained/googlenet_part8_all_xavier_ckpt_56.h5')
2025-06-27 12:58:59.179 | INFO     | __main__:main:166 - Model Summary: Params: 99.00M, Gflops: 793.21
2025-06-27 12:58:59.179 | INFO     | yolox.data.datasets.mot:__init__:39 - loading annotations into memory...
2025-06-27 12:58:59.256 | INFO     | yolox.data.datasets.mot:__init__:39 - Done (t=0.08s)
2025-06-27 12:58:59.256 | INFO     | pycocotools.coco:__init__:88 - creating index...
2025-06-27 12:58:59.259 | INFO     | pycocotools.coco:__init__:88 - index created!
2025-06-27 12:58:59.736 | INFO     | __main__:main:190 - loading checkpoint
2025-06-27 12:59:00.013 | INFO     | __main__:main:195 - loaded checkpoint done.
2025-06-27 12:59:00.013 | INFO     | __main__:main:201 - 	Fusing model...
2025-06-27 12:59:00.813 | ERROR    | yolox.core.launch:launch:90 - An error has been caught in function 'launch', process 'MainProcess' (24715), thread 'MainThread' (139848540520576):
Traceback (most recent call last):

  File "/home/stas/ID-REID/ByteTrack/tools/track_motdt.py", line 285, in <module>
    launch(
    └ <function launch at 0x7f304a122f70>

> File "/home/stas/ID-REID/ByteTrack/yolox/core/launch.py", line 90, in launch
    main_func(*args)
    │          └ (╒══════════════════╤══════════════════════════════════════════════════════════════════════════════════════════════╕
    │            │ keys  ...
    └ <function main at 0x7f2ff7d74430>

  File "/home/stas/ID-REID/ByteTrack/tools/track_motdt.py", line 219, in main
    *_, summary = evaluator.evaluate_motdt(
                  │         └ <function MOTEvaluator.evaluate_motdt at 0x7f2ffa6768b0>
                  └ <yolox.evaluators.mot_evaluator.MOTEvaluator object at 0x7f305cae0190>

  File "/home/stas/ID-REID/ByteTrack/yolox/evaluators/mot_evaluator.py", line 518, in evaluate_motdt
    tracker = OnlineTracker(model_folder, min_cls_score=self.args.track_thresh)
              │             │                           │    │    └ 0.6
              │             │                           │    └ Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_ra...
              │             │                           └ <yolox.evaluators.mot_evaluator.MOTEvaluator object at 0x7f305cae0190>
              │             └ 'pretrained/googlenet_part8_all_xavier_ckpt_56.h5'
              └ <class 'yolox.motdt_tracker.motdt_tracker.OnlineTracker'>

  File "/home/stas/ID-REID/ByteTrack/yolox/motdt_tracker/motdt_tracker.py", line 200, in __init__
    self.reid_model = load_reid_model(model_folder)
    │                 │               └ 'pretrained/googlenet_part8_all_xavier_ckpt_56.h5'
    │                 └ <function load_reid_model at 0x7f2ffa66f1f0>
    └ <yolox.motdt_tracker.motdt_tracker.OnlineTracker object at 0x7f307412e0a0>

  File "/home/stas/ID-REID/ByteTrack/yolox/motdt_tracker/reid_model.py", line 237, in load_reid_model
    load_net(ckpt, model)
    │        │     └ Model(
    │        │         (feat_conv): GoogLeNet(
    │        │           (pre_layers): Sequential(
    │        │             (0): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), pa...
    │        └ 'pretrained/googlenet_part8_all_xavier_ckpt_56.h5'
    └ <function load_net at 0x7f2ffa66f160>

  File "/home/stas/ID-REID/ByteTrack/yolox/motdt_tracker/reid_model.py", line 36, in load_net
    with h5py.File(fname, mode='r') as h5f:
         │    │    └ 'pretrained/googlenet_part8_all_xavier_ckpt_56.h5'
         │    └ <class 'h5py._hl.files.File'>
         └ <module 'h5py' from '/home/stas/ID-REID/ByteTrack/.venv/lib/python3.9/site-packages/h5py/__init__.py'>

  File "/home/stas/ID-REID/ByteTrack/.venv/lib/python3.9/site-packages/h5py/_hl/files.py", line 564, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
          │        │     │     │               │     │          └ False
          │        │     │     │               │     └ None
          │        │     │     │               └ <h5py.h5p.PropFAID object at 0x7f3085e21310>
          │        │     │     └ None
          │        │     └ 'r'
          │        └ b'pretrained/googlenet_part8_all_xavier_ckpt_56.h5'
          └ <function make_fid at 0x7f30853fa790>
  File "/home/stas/ID-REID/ByteTrack/.venv/lib/python3.9/site-packages/h5py/_hl/files.py", line 238, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
          │   │    │     │           └ <h5py.h5p.PropFAID object at 0x7f3085e21310>
          │   │    │     └ 0
          │   │    └ b'pretrained/googlenet_part8_all_xavier_ckpt_56.h5'
          │   └ <cyfunction open at 0x7f30855f3700>
          └ <module 'h5py.h5f' from '/home/stas/ID-REID/ByteTrack/.venv/lib/python3.9/site-packages/h5py/h5f.cpython-39-x86_64-linux-gnu....
  File "h5py/_objects.pyx", line 56, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 57, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 102, in h5py.h5f.open

FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'pretrained/googlenet_part8_all_xavier_ckpt_56.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-06-27 13:01:15.908 | INFO     | __main__:main:156 - Args: Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_rank=0, num_machines=1, machine_rank=0, exp_file='exps/example/mot/yolox_x_mix_det.py', fp16=True, fuse=True, trt=False, test=False, speed=False, opts=[], ckpt='pretrained/bytetrack_x_mot17.pth.tar', conf=0.1, nms=0.7, tsize=None, seed=None, track_thresh=0.6, track_buffer=30, match_thresh=0.9, min_box_area=100, model_folder='pretrained/googlenet_part8_all_xavier_ckpt_56.h5')
2025-06-27 13:01:16.304 | INFO     | __main__:main:166 - Model Summary: Params: 99.00M, Gflops: 793.21
2025-06-27 13:01:16.305 | INFO     | yolox.data.datasets.mot:__init__:39 - loading annotations into memory...
2025-06-27 13:01:16.379 | INFO     | yolox.data.datasets.mot:__init__:39 - Done (t=0.07s)
2025-06-27 13:01:16.379 | INFO     | pycocotools.coco:__init__:88 - creating index...
2025-06-27 13:01:16.382 | INFO     | pycocotools.coco:__init__:88 - index created!
2025-06-27 13:01:16.859 | INFO     | __main__:main:190 - loading checkpoint
2025-06-27 13:01:17.123 | INFO     | __main__:main:195 - loaded checkpoint done.
2025-06-27 13:01:17.124 | INFO     | __main__:main:201 - 	Fusing model...
2025-06-27 13:01:20.193 | ERROR    | yolox.core.launch:launch:90 - An error has been caught in function 'launch', process 'MainProcess' (26095), thread 'MainThread' (139950618968192):
Traceback (most recent call last):

  File "/home/stas/ID-REID/ByteTrack/tools/track_motdt.py", line 285, in <module>
    launch(
    └ <function launch at 0x7f480e6baf70>

> File "/home/stas/ID-REID/ByteTrack/yolox/core/launch.py", line 90, in launch
    main_func(*args)
    │          └ (╒══════════════════╤══════════════════════════════════════════════════════════════════════════════════════════════╕
    │            │ keys  ...
    └ <function main at 0x7f47bc30e430>

  File "/home/stas/ID-REID/ByteTrack/tools/track_motdt.py", line 219, in main
    *_, summary = evaluator.evaluate_motdt(
                  │         └ <function MOTEvaluator.evaluate_motdt at 0x7f47bec0d8b0>
                  └ <yolox.evaluators.mot_evaluator.MOTEvaluator object at 0x7f484377f250>

  File "/home/stas/ID-REID/ByteTrack/yolox/evaluators/mot_evaluator.py", line 559, in evaluate_motdt
    online_targets = tracker.update(outputs[0], info_imgs, self.img_size, img_file_name[0])
                     │       │      │           │          │    │         └ ['KITTI-17/img1/000001.jpg']
                     │       │      │           │          │    └ (800, 1440)
                     │       │      │           │          └ <yolox.evaluators.mot_evaluator.MOTEvaluator object at 0x7f484377f250>
                     │       │      │           └ [tensor([370]), tensor([1224]), tensor([1]), tensor([1]), ['KITTI-17/img1/000001.jpg']]
                     │       │      └ [tensor([[4.4650e+02, 1.8025e+02, 5.8650e+02, 4.2375e+02, 9.9805e-01, 9.4434e-01,
                     │       │                 0.0000e+00],
                     │       │                [5.2800e+02, ...
                     │       └ <function OnlineTracker.update at 0x7f47bec0d4c0>
                     └ <yolox.motdt_tracker.motdt_tracker.OnlineTracker object at 0x7f484a591730>

  File "/home/stas/ID-REID/ByteTrack/yolox/motdt_tracker/motdt_tracker.py", line 263, in update
    features = extract_reid_features(self.reid_model, image, tlbrs)
               │                     │    │           │      └ [array([379.5249939, 153.2124939, 498.5249939, 360.1875   ]), array([448.79998779, 142.5874939 , 553.34997559, 336.38748169])...
               │                     │    │           └ None
               │                     │    └ Model(
               │                     │        (feat_conv): GoogLeNet(
               │                     │          (pre_layers): Sequential(
               │                     │            (0): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), pa...
               │                     └ <yolox.motdt_tracker.motdt_tracker.OnlineTracker object at 0x7f484a591730>
               └ <function extract_reid_features at 0x7f47bec07700>

  File "/home/stas/ID-REID/ByteTrack/yolox/motdt_tracker/reid_model.py", line 263, in extract_reid_features
    patches = extract_image_patches(image, tlbrs)
              │                     │      └ [array([379.5249939, 153.2124939, 498.5249939, 360.1875   ]), array([448.79998779, 142.5874939 , 553.34997559, 336.38748169])...
              │                     └ None
              └ <function extract_image_patches at 0x7f47bec07670>

  File "/home/stas/ID-REID/ByteTrack/yolox/motdt_tracker/reid_model.py", line 254, in extract_image_patches
    bboxes = clip_boxes(bboxes, image.shape)
             │          │       └ None
             │          └ array([[380, 153, 499, 360],
             │                   [449, 143, 553, 336],
             │                   [482, 144, 504, 203],
             │                   [544, 146, 563, 193]])
             └ <function clip_boxes at 0x7f47bebfef70>

AttributeError: 'NoneType' object has no attribute 'shape'
2025-06-27 13:03:48.192 | INFO     | __main__:main:156 - Args: Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_rank=0, num_machines=1, machine_rank=0, exp_file='exps/example/mot/yolox_x_mix_det.py', fp16=True, fuse=True, trt=False, test=False, speed=False, opts=[], ckpt='pretrained/bytetrack_x_mot17.pth.tar', conf=0.1, nms=0.7, tsize=None, seed=None, track_thresh=0.6, track_buffer=30, match_thresh=0.9, min_box_area=100, model_folder='pretrained/googlenet_part8_all_xavier_ckpt_56.h5')
2025-06-27 13:03:48.587 | INFO     | __main__:main:166 - Model Summary: Params: 99.00M, Gflops: 793.21
2025-06-27 13:03:48.588 | INFO     | yolox.data.datasets.mot:__init__:39 - loading annotations into memory...
2025-06-27 13:03:48.662 | INFO     | yolox.data.datasets.mot:__init__:39 - Done (t=0.07s)
2025-06-27 13:03:48.663 | INFO     | pycocotools.coco:__init__:88 - creating index...
2025-06-27 13:03:48.666 | INFO     | pycocotools.coco:__init__:88 - index created!
2025-06-27 13:03:49.137 | INFO     | __main__:main:190 - loading checkpoint
2025-06-27 13:03:49.408 | INFO     | __main__:main:195 - loaded checkpoint done.
2025-06-27 13:03:49.408 | INFO     | __main__:main:201 - 	Fusing model...
2025-06-27 13:03:52.412 | ERROR    | yolox.core.launch:launch:90 - An error has been caught in function 'launch', process 'MainProcess' (27607), thread 'MainThread' (140234566799488):
Traceback (most recent call last):

  File "/home/stas/ID-REID/ByteTrack/tools/track_motdt.py", line 285, in <module>
    launch(
    └ <function launch at 0x7f8a2b082040>

> File "/home/stas/ID-REID/ByteTrack/yolox/core/launch.py", line 90, in launch
    main_func(*args)
    │          └ (╒══════════════════╤══════════════════════════════════════════════════════════════════════════════════════════════╕
    │            │ keys  ...
    └ <function main at 0x7f89d8ccd4c0>

  File "/home/stas/ID-REID/ByteTrack/tools/track_motdt.py", line 219, in main
    *_, summary = evaluator.evaluate_motdt(
                  │         └ <function MOTEvaluator.evaluate_motdt at 0x7f89db550940>
                  └ <yolox.evaluators.mot_evaluator.MOTEvaluator object at 0x7f8a5d983370>

  File "/home/stas/ID-REID/ByteTrack/yolox/evaluators/mot_evaluator.py", line 559, in evaluate_motdt
    online_targets = tracker.update(outputs[0], info_imgs, self.img_size, img_file_name[0])
                     │       │      │           │          │    │         └ ['KITTI-17/img1/000001.jpg']
                     │       │      │           │          │    └ (800, 1440)
                     │       │      │           │          └ <yolox.evaluators.mot_evaluator.MOTEvaluator object at 0x7f8a5d983370>
                     │       │      │           └ [tensor([370]), tensor([1224]), tensor([1]), tensor([1]), ['KITTI-17/img1/000001.jpg']]
                     │       │      └ [tensor([[4.4650e+02, 1.8025e+02, 5.8650e+02, 4.2375e+02, 9.9805e-01, 9.4434e-01,
                     │       │                 0.0000e+00],
                     │       │                [5.2800e+02, ...
                     │       └ <function OnlineTracker.update at 0x7f89db550550>
                     └ <yolox.motdt_tracker.motdt_tracker.OnlineTracker object at 0x7f8a66f5a1c0>

  File "/home/stas/ID-REID/ByteTrack/yolox/motdt_tracker/motdt_tracker.py", line 263, in update
    features = extract_reid_features(self.reid_model, image, tlbrs)
               │                     │    │           │      └ [array([379.5249939, 153.2124939, 498.5249939, 360.1875   ]), array([448.79998779, 142.5874939 , 553.34997559, 336.38748169])...
               │                     │    │           └ None
               │                     │    └ Model(
               │                     │        (feat_conv): GoogLeNet(
               │                     │          (pre_layers): Sequential(
               │                     │            (0): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), pa...
               │                     └ <yolox.motdt_tracker.motdt_tracker.OnlineTracker object at 0x7f8a66f5a1c0>
               └ <function extract_reid_features at 0x7f89db5c7790>

  File "/home/stas/ID-REID/ByteTrack/yolox/motdt_tracker/reid_model.py", line 263, in extract_reid_features
    patches = extract_image_patches(image, tlbrs)
              │                     │      └ [array([379.5249939, 153.2124939, 498.5249939, 360.1875   ]), array([448.79998779, 142.5874939 , 553.34997559, 336.38748169])...
              │                     └ None
              └ <function extract_image_patches at 0x7f89db5c7700>

  File "/home/stas/ID-REID/ByteTrack/yolox/motdt_tracker/reid_model.py", line 254, in extract_image_patches
    bboxes = clip_boxes(bboxes, image.shape)
             │          │       └ None
             │          └ array([[380, 153, 499, 360],
             │                   [449, 143, 553, 336],
             │                   [482, 144, 504, 203],
             │                   [544, 146, 563, 193]])
             └ <function clip_boxes at 0x7f89db5c7040>

AttributeError: 'NoneType' object has no attribute 'shape'
2025-06-27 13:07:51.562 | INFO     | __main__:main:156 - Args: Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_rank=0, num_machines=1, machine_rank=0, exp_file='exps/example/mot/yolox_x_mix_det.py', fp16=True, fuse=True, trt=False, test=False, speed=False, opts=[], ckpt='pretrained/bytetrack_x_mot17.pth.tar', conf=0.1, nms=0.7, tsize=None, seed=None, track_thresh=0.6, track_buffer=30, match_thresh=0.9, min_box_area=100, model_folder='pretrained/googlenet_part8_all_xavier_ckpt_56.h5')
2025-06-27 13:07:51.956 | INFO     | __main__:main:166 - Model Summary: Params: 99.00M, Gflops: 793.21
2025-06-27 13:07:51.957 | INFO     | yolox.data.datasets.mot:__init__:39 - loading annotations into memory...
2025-06-27 13:07:52.034 | INFO     | yolox.data.datasets.mot:__init__:39 - Done (t=0.08s)
2025-06-27 13:07:52.034 | INFO     | pycocotools.coco:__init__:88 - creating index...
2025-06-27 13:07:52.037 | INFO     | pycocotools.coco:__init__:88 - index created!
2025-06-27 13:07:52.505 | INFO     | __main__:main:190 - loading checkpoint
2025-06-27 13:07:52.772 | INFO     | __main__:main:195 - loaded checkpoint done.
2025-06-27 13:07:52.772 | INFO     | __main__:main:201 - 	Fusing model...
2025-06-27 13:07:55.666 | ERROR    | yolox.core.launch:launch:90 - An error has been caught in function 'launch', process 'MainProcess' (29633), thread 'MainThread' (140359202201728):
Traceback (most recent call last):

  File "/home/stas/ID-REID/ByteTrack/tools/track_motdt.py", line 285, in <module>
    launch(
    └ <function launch at 0x7fa72fe17040>

> File "/home/stas/ID-REID/ByteTrack/yolox/core/launch.py", line 90, in launch
    main_func(*args)
    │          └ (╒══════════════════╤══════════════════════════════════════════════════════════════════════════════════════════════╕
    │            │ keys  ...
    └ <function main at 0x7fa6dda624c0>

  File "/home/stas/ID-REID/ByteTrack/tools/track_motdt.py", line 219, in main
    *_, summary = evaluator.evaluate_motdt(
                  │         └ <function MOTEvaluator.evaluate_motdt at 0x7fa6e035a9d0>
                  └ <yolox.evaluators.mot_evaluator.MOTEvaluator object at 0x7fa6dda89250>

  File "/home/stas/ID-REID/ByteTrack/yolox/evaluators/mot_evaluator.py", line 559, in evaluate_motdt
    online_targets = tracker.update(outputs[0], info_imgs, self.img_size, img_file_name[0])
                     │       │      │           │          │    │         └ ['KITTI-17/img1/000001.jpg']
                     │       │      │           │          │    └ (800, 1440)
                     │       │      │           │          └ <yolox.evaluators.mot_evaluator.MOTEvaluator object at 0x7fa6dda89250>
                     │       │      │           └ [tensor([370]), tensor([1224]), tensor([1]), tensor([1]), ['KITTI-17/img1/000001.jpg']]
                     │       │      └ [tensor([[4.4650e+02, 1.8025e+02, 5.8650e+02, 4.2375e+02, 9.9805e-01, 9.4434e-01,
                     │       │                 0.0000e+00],
                     │       │                [5.2800e+02, ...
                     │       └ <function OnlineTracker.update at 0x7fa6e035a5e0>
                     └ <yolox.motdt_tracker.motdt_tracker.OnlineTracker object at 0x7fa76bce7610>

  File "/home/stas/ID-REID/ByteTrack/yolox/motdt_tracker/motdt_tracker.py", line 264, in update
    features = extract_reid_features(self.reid_model, image, tlbrs)
               │                     │    │           │      └ [array([379.5249939, 153.2124939, 498.5249939, 360.1875   ]), array([448.79998779, 142.5874939 , 553.34997559, 336.38748169])...
               │                     │    │           └ None
               │                     │    └ Model(
               │                     │        (feat_conv): GoogLeNet(
               │                     │          (pre_layers): Sequential(
               │                     │            (0): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), pa...
               │                     └ <yolox.motdt_tracker.motdt_tracker.OnlineTracker object at 0x7fa76bce7610>
               └ <function extract_reid_features at 0x7fa6e0355820>

  File "/home/stas/ID-REID/ByteTrack/yolox/motdt_tracker/reid_model.py", line 263, in extract_reid_features
    patches = extract_image_patches(image, tlbrs)
              │                     │      └ [array([379.5249939, 153.2124939, 498.5249939, 360.1875   ]), array([448.79998779, 142.5874939 , 553.34997559, 336.38748169])...
              │                     └ None
              └ <function extract_image_patches at 0x7fa6e0355790>

  File "/home/stas/ID-REID/ByteTrack/yolox/motdt_tracker/reid_model.py", line 254, in extract_image_patches
    bboxes = clip_boxes(bboxes, image.shape)
             │          │       └ None
             │          └ array([[380, 153, 499, 360],
             │                   [449, 143, 553, 336],
             │                   [482, 144, 504, 203],
             │                   [544, 146, 563, 193]])
             └ <function clip_boxes at 0x7fa6e03550d0>

AttributeError: 'NoneType' object has no attribute 'shape'
2025-06-27 13:08:23.714 | INFO     | __main__:main:156 - Args: Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_rank=0, num_machines=1, machine_rank=0, exp_file='exps/example/mot/yolox_x_mix_det.py', fp16=True, fuse=True, trt=False, test=False, speed=False, opts=[], ckpt='pretrained/bytetrack_x_mot17.pth.tar', conf=0.1, nms=0.7, tsize=None, seed=None, track_thresh=0.6, track_buffer=30, match_thresh=0.9, min_box_area=100, model_folder='pretrained/googlenet_part8_all_xavier_ckpt_56.h5')
2025-06-27 13:08:24.111 | INFO     | __main__:main:166 - Model Summary: Params: 99.00M, Gflops: 793.21
2025-06-27 13:08:24.111 | INFO     | yolox.data.datasets.mot:__init__:39 - loading annotations into memory...
2025-06-27 13:08:24.186 | INFO     | yolox.data.datasets.mot:__init__:39 - Done (t=0.07s)
2025-06-27 13:08:24.186 | INFO     | pycocotools.coco:__init__:88 - creating index...
2025-06-27 13:08:24.189 | INFO     | pycocotools.coco:__init__:88 - index created!
2025-06-27 13:08:24.663 | INFO     | __main__:main:190 - loading checkpoint
2025-06-27 13:08:24.933 | INFO     | __main__:main:195 - loaded checkpoint done.
2025-06-27 13:08:24.933 | INFO     | __main__:main:201 - 	Fusing model...
2025-06-27 13:08:27.841 | ERROR    | yolox.core.launch:launch:90 - An error has been caught in function 'launch', process 'MainProcess' (30133), thread 'MainThread' (139977025904768):
Traceback (most recent call last):

  File "/home/stas/ID-REID/ByteTrack/tools/track_motdt.py", line 285, in <module>
    launch(
    └ <function launch at 0x7f4e3465f040>

> File "/home/stas/ID-REID/ByteTrack/yolox/core/launch.py", line 90, in launch
    main_func(*args)
    │          └ (╒══════════════════╤══════════════════════════════════════════════════════════════════════════════════════════════╕
    │            │ keys  ...
    └ <function main at 0x7f4de22aa4c0>

  File "/home/stas/ID-REID/ByteTrack/tools/track_motdt.py", line 219, in main
    *_, summary = evaluator.evaluate_motdt(
                  │         └ <function MOTEvaluator.evaluate_motdt at 0x7f4de4b9b9d0>
                  └ <yolox.evaluators.mot_evaluator.MOTEvaluator object at 0x7f4e68f1e340>

  File "/home/stas/ID-REID/ByteTrack/yolox/evaluators/mot_evaluator.py", line 559, in evaluate_motdt
    online_targets = tracker.update(outputs[0], info_imgs, self.img_size, img_file_name[0])
                     │       │      │           │          │    │         └ ['KITTI-17/img1/000001.jpg']
                     │       │      │           │          │    └ (800, 1440)
                     │       │      │           │          └ <yolox.evaluators.mot_evaluator.MOTEvaluator object at 0x7f4e68f1e340>
                     │       │      │           └ [tensor([370]), tensor([1224]), tensor([1]), tensor([1]), ['KITTI-17/img1/000001.jpg']]
                     │       │      └ [tensor([[4.4650e+02, 1.8025e+02, 5.8650e+02, 4.2375e+02, 9.9805e-01, 9.4434e-01,
                     │       │                 0.0000e+00],
                     │       │                [5.2800e+02, ...
                     │       └ <function OnlineTracker.update at 0x7f4de4b9b5e0>
                     └ <yolox.motdt_tracker.motdt_tracker.OnlineTracker object at 0x7f4e704ef640>

  File "/home/stas/ID-REID/ByteTrack/yolox/motdt_tracker/motdt_tracker.py", line 264, in update
    features = extract_reid_features(self.reid_model, image, tlbrs)
               │                     │    │           │      └ [array([379.5249939, 153.2124939, 498.5249939, 360.1875   ]), array([448.79998779, 142.5874939 , 553.34997559, 336.38748169])...
               │                     │    │           └ None
               │                     │    └ Model(
               │                     │        (feat_conv): GoogLeNet(
               │                     │          (pre_layers): Sequential(
               │                     │            (0): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), pa...
               │                     └ <yolox.motdt_tracker.motdt_tracker.OnlineTracker object at 0x7f4e704ef640>
               └ <function extract_reid_features at 0x7f4de4b9d820>

  File "/home/stas/ID-REID/ByteTrack/yolox/motdt_tracker/reid_model.py", line 263, in extract_reid_features
    patches = extract_image_patches(image, tlbrs)
              │                     │      └ [array([379.5249939, 153.2124939, 498.5249939, 360.1875   ]), array([448.79998779, 142.5874939 , 553.34997559, 336.38748169])...
              │                     └ None
              └ <function extract_image_patches at 0x7f4de4b9d790>

  File "/home/stas/ID-REID/ByteTrack/yolox/motdt_tracker/reid_model.py", line 254, in extract_image_patches
    bboxes = clip_boxes(bboxes, image.shape)
             │          │       └ None
             │          └ array([[380, 153, 499, 360],
             │                   [449, 143, 553, 336],
             │                   [482, 144, 504, 203],
             │                   [544, 146, 563, 193]])
             └ <function clip_boxes at 0x7f4de4b9d0d0>

AttributeError: 'NoneType' object has no attribute 'shape'
2025-06-27 13:15:00.038 | INFO     | __main__:main:156 - Args: Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_rank=0, num_machines=1, machine_rank=0, exp_file='exps/example/mot/yolox_x_mix_det.py', fp16=True, fuse=True, trt=False, test=False, speed=False, opts=[], ckpt='pretrained/bytetrack_x_mot17.pth.tar', conf=0.1, nms=0.7, tsize=None, seed=None, track_thresh=0.6, track_buffer=30, match_thresh=0.9, min_box_area=100, model_folder='pretrained/googlenet_part8_all_xavier_ckpt_56.h5')
2025-06-27 13:15:00.436 | INFO     | __main__:main:166 - Model Summary: Params: 99.00M, Gflops: 793.21
2025-06-27 13:15:00.437 | INFO     | yolox.data.datasets.mot:__init__:39 - loading annotations into memory...
2025-06-27 13:15:00.512 | INFO     | yolox.data.datasets.mot:__init__:39 - Done (t=0.07s)
2025-06-27 13:15:00.512 | INFO     | pycocotools.coco:__init__:88 - creating index...
2025-06-27 13:15:00.515 | INFO     | pycocotools.coco:__init__:88 - index created!
2025-06-27 13:15:00.993 | INFO     | __main__:main:190 - loading checkpoint
2025-06-27 13:15:01.264 | INFO     | __main__:main:195 - loaded checkpoint done.
2025-06-27 13:15:01.264 | INFO     | __main__:main:201 - 	Fusing model...
2025-06-27 13:15:18.635 | INFO     | yolox.evaluators.mot_evaluator:write_results:39 - save results to ./YOLOX_outputs/yolox_x_mix_det/track_results_motdt/KITTI-17.txt
2025-06-27 13:16:10.990 | INFO     | yolox.evaluators.mot_evaluator:write_results:39 - save results to ./YOLOX_outputs/yolox_x_mix_det/track_results_motdt/MOT16-09.txt
2025-06-27 13:17:43.990 | INFO     | yolox.evaluators.mot_evaluator:write_results:39 - save results to ./YOLOX_outputs/yolox_x_mix_det/track_results_motdt/MOT16-11.txt
2025-06-27 13:18:58.062 | INFO     | yolox.evaluators.mot_evaluator:write_results:39 - save results to ./YOLOX_outputs/yolox_x_mix_det/track_results_motdt/PETS09-S2L1.txt
2025-06-27 13:19:04.789 | INFO     | yolox.evaluators.mot_evaluator:write_results:39 - save results to ./YOLOX_outputs/yolox_x_mix_det/track_results_motdt/TUD-Campus.txt
2025-06-27 13:19:20.678 | INFO     | yolox.evaluators.mot_evaluator:write_results:39 - save results to ./YOLOX_outputs/yolox_x_mix_det/track_results_motdt/TUD-Stadtmitte.txt
2025-06-27 13:19:20.713 | INFO     | yolox.evaluators.mot_evaluator:evaluate_prediction:628 - Evaluate in main process...
2025-06-27 13:19:20.913 | INFO     | yolox.evaluators.mot_evaluator:evaluate_prediction:657 - Loading and preparing results...
2025-06-27 13:19:21.003 | INFO     | yolox.evaluators.mot_evaluator:evaluate_prediction:657 - DONE (t=0.09s)
2025-06-27 13:19:21.003 | INFO     | pycocotools.coco:loadRes:363 - creating index...
2025-06-27 13:19:21.008 | INFO     | pycocotools.coco:loadRes:363 - index created!
2025-06-27 13:19:21.175 | INFO     | __main__:main:222 - 
Average forward time: 73.53 ms, Average track time: 19.17 ms, Average inference time: 92.70 ms
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.593
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.917
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.596
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.002
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.405
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.719
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.091
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.670
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.704
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.300
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.539
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.798

2025-06-27 13:19:21.176 | INFO     | __main__:main:235 - Found 6 groundtruths and 6 test files.
2025-06-27 13:19:21.176 | INFO     | __main__:main:236 - Available LAP solvers ['lap', 'scipy']
2025-06-27 13:19:21.176 | INFO     | __main__:main:237 - Default LAP solver 'lap'
2025-06-27 13:19:21.176 | INFO     | __main__:main:238 - Loading files.
2025-06-27 13:19:21.432 | INFO     | __main__:compare_dataframes:119 - Comparing TUD-Stadtmitte...
2025-06-27 13:19:21.473 | INFO     | __main__:compare_dataframes:119 - Comparing TUD-Campus...
2025-06-27 13:19:21.489 | INFO     | __main__:compare_dataframes:119 - Comparing KITTI-17...
2025-06-27 13:19:21.521 | INFO     | __main__:compare_dataframes:119 - Comparing MOT16-11...
2025-06-27 13:19:21.780 | INFO     | __main__:compare_dataframes:119 - Comparing MOT16-09...
2025-06-27 13:19:21.903 | INFO     | __main__:compare_dataframes:119 - Comparing PETS09-S2L1...
2025-06-27 13:19:22.071 | INFO     | __main__:main:246 - Running metrics
2025-06-27 13:19:22.324 | INFO     | __main__:main:271 - Completed
